/* ============================================================
   中国語単語集データ
   初級 / 中級 / 上級レベル
   ============================================================ */

const WORD_SETS = {
  beginner: {
    label: '初級レベル',
    description: '日常会話の基本単語（約100語）',
    color: '#cc0000',
    words: [
      // 挨拶
      { word: '你好',     reading: 'nǐ hǎo',        japanese: 'こんにちは',           example: '你好！很高兴认识你。',         notes: '挨拶' },
      { word: '再见',     reading: 'zàijiàn',        japanese: 'さようなら',           example: '明天见！再见！',               notes: '挨拶' },
      { word: '谢谢',     reading: 'xièxie',         japanese: 'ありがとう',           example: '谢谢你的帮助。',               notes: '挨拶' },
      { word: '对不起',   reading: 'duìbuqǐ',        japanese: 'すみません',           example: '对不起，我来晚了。',           notes: '挨拶' },
      { word: '没关系',   reading: 'méiguānxi',      japanese: '大丈夫です',           example: '没关系，不要担心。',           notes: '挨拶' },
      { word: '早上好',   reading: 'zǎoshang hǎo',  japanese: 'おはようございます',   example: '早上好！今天天气不错。',       notes: '挨拶' },
      { word: '晚上好',   reading: 'wǎnshang hǎo',  japanese: 'こんばんは',           example: '晚上好！你吃饭了吗？',         notes: '挨拶' },
      { word: '晚安',     reading: "wǎn'ān",         japanese: 'おやすみなさい',       example: '晚安！好好休息。',             notes: '挨拶' },
      { word: '你好吗',   reading: 'nǐ hǎo ma',      japanese: '元気ですか',           example: '你好吗？我很好。',             notes: '挨拶' },
      { word: '我很好',   reading: 'wǒ hěn hǎo',     japanese: '元気です',             example: '我很好，谢谢你！',             notes: '挨拶' },
      // 代名詞
      { word: '我',       reading: 'wǒ',             japanese: '私',                   example: '我叫山田太郎。',               notes: '代名詞' },
      { word: '你',       reading: 'nǐ',             japanese: 'あなた',               example: '你叫什么名字？',               notes: '代名詞' },
      { word: '他',       reading: 'tā',             japanese: '彼',                   example: '他是我的朋友。',               notes: '代名詞' },
      { word: '她',       reading: 'tā',             japanese: '彼女',                 example: '她很漂亮。',                   notes: '代名詞' },
      { word: '我们',     reading: 'wǒmen',          japanese: '私たち',               example: '我们一起去吧。',               notes: '代名詞' },
      { word: '你们',     reading: 'nǐmen',          japanese: 'あなたたち',           example: '你们都是学生吗？',             notes: '代名詞' },
      { word: '他们',     reading: 'tāmen',          japanese: '彼ら',                 example: '他们是一家人。',               notes: '代名詞' },
      { word: '这',       reading: 'zhè',            japanese: 'これ',                 example: '这是什么？',                   notes: '代名詞' },
      { word: '那',       reading: 'nà',             japanese: 'あれ',                 example: '那是我的书包。',               notes: '代名詞' },
      { word: '什么',     reading: 'shénme',         japanese: '何',                   example: '你想吃什么？',                 notes: '代名詞' },
      // 数字
      { word: '一',       reading: 'yī',             japanese: '1',                    example: '我有一本书。',                 notes: '数字' },
      { word: '二',       reading: 'èr',             japanese: '2',                    example: '我有两个苹果。',               notes: '数字' },
      { word: '三',       reading: 'sān',            japanese: '3',                    example: '我住在三楼。',                 notes: '数字' },
      { word: '四',       reading: 'sì',             japanese: '4',                    example: '今天是四月。',                 notes: '数字' },
      { word: '五',       reading: 'wǔ',             japanese: '5',                    example: '我有五个朋友。',               notes: '数字' },
      { word: '六',       reading: 'liù',            japanese: '6',                    example: '今天是六号。',                 notes: '数字' },
      { word: '七',       reading: 'qī',             japanese: '7',                    example: '一个星期有七天。',             notes: '数字' },
      { word: '八',       reading: 'bā',             japanese: '8',                    example: '我八点上班。',                 notes: '数字' },
      { word: '九',       reading: 'jiǔ',            japanese: '9',                    example: '九月是秋天。',                 notes: '数字' },
      { word: '十',       reading: 'shí',            japanese: '10',                   example: '十分钟后我到。',               notes: '数字' },
      { word: '百',       reading: 'bǎi',            japanese: '百',                   example: '这件衣服一百块。',             notes: '数字' },
      { word: '千',       reading: 'qiān',           japanese: '千',                   example: '一千个人参加了活动。',         notes: '数字' },
      { word: '万',       reading: 'wàn',            japanese: '万',                   example: '这套房子要一百万。',           notes: '数字' },
      // 基本動詞
      { word: '是',       reading: 'shì',            japanese: 'です・である',         example: '我是日本人。',                 notes: '基本動詞' },
      { word: '有',       reading: 'yǒu',            japanese: 'ある・持っている',     example: '我有一只猫。',                 notes: '基本動詞' },
      { word: '在',       reading: 'zài',            japanese: 'いる・ある',           example: '我在家里。',                   notes: '基本動詞' },
      { word: '去',       reading: 'qù',             japanese: '行く',                 example: '我去学校。',                   notes: '基本動詞' },
      { word: '来',       reading: 'lái',            japanese: '来る',                 example: '他来了。',                     notes: '基本動詞' },
      { word: '吃',       reading: 'chī',            japanese: '食べる',               example: '我想吃饺子。',                 notes: '基本動詞' },
      { word: '喝',       reading: 'hē',             japanese: '飲む',                 example: '你想喝什么？',                 notes: '基本動詞' },
      { word: '睡',       reading: 'shuì',           japanese: '眠る',                 example: '我晚上十点睡觉。',             notes: '基本動詞' },
      { word: '工作',     reading: 'gōngzuò',        japanese: '働く',                 example: '我在公司工作。',               notes: '基本動詞' },
      { word: '学习',     reading: 'xuéxí',          japanese: '勉強する',             example: '我在学习中文。',               notes: '基本動詞' },
      { word: '说',       reading: 'shuō',           japanese: '話す',                 example: '她会说英语。',                 notes: '基本動詞' },
      { word: '听',       reading: 'tīng',           japanese: '聴く',                 example: '我喜欢听音乐。',               notes: '基本動詞' },
      { word: '看',       reading: 'kàn',            japanese: '見る・読む',           example: '我看电视。',                   notes: '基本動詞' },
      { word: '写',       reading: 'xiě',            japanese: '書く',                 example: '我在写作业。',                 notes: '基本動詞' },
      { word: '买',       reading: 'mǎi',            japanese: '買う',                 example: '我去超市买东西。',             notes: '基本動詞' },
      { word: '卖',       reading: 'mài',            japanese: '売る',                 example: '他在市场卖蔬菜。',             notes: '基本動詞' },
      { word: '喜欢',     reading: 'xǐhuān',         japanese: '好きである',           example: '我喜欢吃日本料理。',           notes: '基本動詞' },
      { word: '知道',     reading: 'zhīdào',         japanese: '知っている',           example: '你知道这件事吗？',             notes: '基本動詞' },
      { word: '想',       reading: 'xiǎng',          japanese: '思う・したい',         example: '我想去日本旅行。',             notes: '基本動詞' },
      { word: '要',       reading: 'yào',            japanese: '要る・したい',         example: '我要一杯咖啡。',               notes: '基本動詞' },
      // 家族
      { word: '家人',     reading: 'jiārén',         japanese: '家族',                 example: '我的家人都在日本。',           notes: '家族' },
      { word: '爸爸',     reading: 'bàba',           japanese: 'お父さん',             example: '我爸爸是医生。',               notes: '家族' },
      { word: '妈妈',     reading: 'māma',           japanese: 'お母さん',             example: '妈妈做的饭最好吃。',           notes: '家族' },
      { word: '哥哥',     reading: 'gēge',           japanese: 'お兄さん',             example: '我哥哥在东京工作。',           notes: '家族' },
      { word: '弟弟',     reading: 'dìdi',           japanese: '弟',                   example: '弟弟今年上小学。',             notes: '家族' },
      { word: '姐姐',     reading: 'jiějie',         japanese: 'お姉さん',             example: '姐姐比我大三岁。',             notes: '家族' },
      { word: '妹妹',     reading: 'mèimei',         japanese: '妹',                   example: '我妹妹很可爱。',               notes: '家族' },
      { word: '朋友',     reading: 'péngyou',        japanese: '友達',                 example: '他是我最好的朋友。',           notes: '家族' },
      // 場所
      { word: '学校',     reading: 'xuéxiào',        japanese: '学校',                 example: '我每天去学校上课。',           notes: '場所' },
      { word: '家',       reading: 'jiā',            japanese: '家',                   example: '我家在北京。',                 notes: '場所' },
      { word: '公司',     reading: 'gōngsī',         japanese: '会社',                 example: '我在一家大公司工作。',         notes: '場所' },
      { word: '医院',     reading: 'yīyuàn',         japanese: '病院',                 example: '我去医院看病。',               notes: '場所' },
      { word: '银行',     reading: 'yínháng',        japanese: '銀行',                 example: '我去银行取钱。',               notes: '場所' },
      { word: '超市',     reading: 'chāoshì',        japanese: 'スーパー',             example: '超市里有很多东西。',           notes: '場所' },
      { word: '餐厅',     reading: 'cāntīng',        japanese: 'レストラン',           example: '我们去餐厅吃饭吧。',           notes: '場所' },
      { word: '图书馆',   reading: 'túshūguǎn',      japanese: '図書館',               example: '图书馆里有很多书。',           notes: '場所' },
      { word: '公园',     reading: 'gōngyuán',       japanese: '公園',                 example: '我在公园里散步。',             notes: '場所' },
      { word: '车站',     reading: 'chēzhàn',        japanese: '駅',                   example: '我在车站等你。',               notes: '場所' },
      // 食べ物
      { word: '米饭',     reading: 'mǐfàn',          japanese: 'ご飯',                 example: '我每天都吃米饭。',             notes: '食べ物' },
      { word: '面条',     reading: 'miàntiáo',       japanese: '麺',                   example: '我喜欢吃面条。',               notes: '食べ物' },
      { word: '包子',     reading: 'bāozi',          japanese: '肉まん',               example: '早上我吃包子。',               notes: '食べ物' },
      { word: '饺子',     reading: 'jiǎozi',         japanese: '餃子',                 example: '春节我们吃饺子。',             notes: '食べ物' },
      { word: '面包',     reading: 'miànbāo',        japanese: 'パン',                 example: '我早餐吃面包。',               notes: '食べ物' },
      { word: '水果',     reading: 'shuǐguǒ',        japanese: '果物',                 example: '我喜欢吃各种水果。',           notes: '食べ物' },
      { word: '蔬菜',     reading: 'shūcài',         japanese: '野菜',                 example: '蔬菜对身体很好。',             notes: '食べ物' },
      { word: '肉',       reading: 'ròu',            japanese: '肉',                   example: '我不太喜欢吃肉。',             notes: '食べ物' },
      { word: '鱼',       reading: 'yú',             japanese: '魚',                   example: '这条鱼很新鲜。',               notes: '食べ物' },
      { word: '水',       reading: 'shuǐ',           japanese: '水',                   example: '多喝水对身体好。',             notes: '食べ物' },
      { word: '茶',       reading: 'chá',            japanese: 'お茶',                 example: '我每天喝茶。',                 notes: '食べ物' },
      { word: '咖啡',     reading: 'kāfēi',          japanese: 'コーヒー',             example: '我早上喜欢喝咖啡。',           notes: '食べ物' },
      // 形容詞
      { word: '大',       reading: 'dà',             japanese: '大きい',               example: '这个城市很大。',               notes: '形容詞' },
      { word: '小',       reading: 'xiǎo',           japanese: '小さい',               example: '我的房间很小。',               notes: '形容詞' },
      { word: '多',       reading: 'duō',            japanese: '多い',                 example: '今天的作业很多。',             notes: '形容詞' },
      { word: '少',       reading: 'shǎo',           japanese: '少ない',               example: '这里的人很少。',               notes: '形容詞' },
      { word: '好',       reading: 'hǎo',            japanese: '良い',                 example: '今天天气很好。',               notes: '形容詞' },
      { word: '不好',     reading: 'bù hǎo',         japanese: '良くない',             example: '这个结果不好。',               notes: '形容詞' },
      { word: '贵',       reading: 'guì',            japanese: '高い（値段）',         example: '这件衣服太贵了。',             notes: '形容詞' },
      { word: '便宜',     reading: 'piányí',         japanese: '安い',                 example: '这里的东西很便宜。',           notes: '形容詞' },
      { word: '快',       reading: 'kuài',           japanese: '速い',                 example: '他走路很快。',                 notes: '形容詞' },
      { word: '慢',       reading: 'màn',            japanese: '遅い',                 example: '请说慢一点。',                 notes: '形容詞' },
      { word: '高兴',     reading: 'gāoxìng',        japanese: '嬉しい',               example: '见到你我很高兴。',             notes: '形容詞' },
      { word: '难过',     reading: 'nánguò',         japanese: '悲しい',               example: '她听到这个消息很难过。',       notes: '形容詞' },
      { word: '累',       reading: 'lèi',            japanese: '疲れた',               example: '我今天很累。',                 notes: '形容詞' },
      { word: '忙',       reading: 'máng',           japanese: '忙しい',               example: '最近我很忙。',                 notes: '形容詞' },
      { word: '热',       reading: 'rè',             japanese: '暑い',                 example: '今天天气很热。',               notes: '形容詞' },
      { word: '冷',       reading: 'lěng',           japanese: '寒い',                 example: '冬天北京很冷。',               notes: '形容詞' },
    ]
  },

  intermediate: {
    label: '中級レベル',
    description: '中級会話の単語（約100語）',
    color: '#dc2626',
    words: [
      // 職業
      { word: '老师',         reading: 'lǎoshī',           japanese: '先生',             example: '她是一位好老师。',                 notes: '職業' },
      { word: '医生',         reading: 'yīshēng',           japanese: '医者',             example: '我爸爸是一名医生。',               notes: '職業' },
      { word: '工程师',       reading: 'gōngchéngshī',      japanese: 'エンジニア',       example: '他是一位软件工程师。',             notes: '職業' },
      { word: '律师',         reading: 'lǜshī',             japanese: '弁護士',           example: '她是一名律师。',                   notes: '職業' },
      { word: '护士',         reading: 'hùshi',             japanese: '看護師',           example: '护士在医院工作。',                 notes: '職業' },
      { word: '司机',         reading: 'sījī',              japanese: '運転手',           example: '出租车司机很友好。',               notes: '職業' },
      { word: '厨师',         reading: 'chúshī',            japanese: '料理人',           example: '这位厨师做的菜很好吃。',           notes: '職業' },
      { word: '记者',         reading: 'jìzhě',             japanese: '記者',             example: '他是一位新闻记者。',               notes: '職業' },
      { word: '警察',         reading: 'jǐngchá',           japanese: '警察',             example: '警察在维护社会秩序。',             notes: '職業' },
      { word: '商人',         reading: 'shāngrén',          japanese: '商人',             example: '他是一个成功的商人。',             notes: '職業' },
      // 時間
      { word: '今天',         reading: 'jīntiān',           japanese: '今日',             example: '今天天气很好。',                   notes: '時間' },
      { word: '明天',         reading: 'míngtiān',          japanese: '明日',             example: '明天我们去旅行。',                 notes: '時間' },
      { word: '昨天',         reading: 'zuótiān',           japanese: '昨日',             example: '昨天我去了图书馆。',               notes: '時間' },
      { word: '现在',         reading: 'xiànzài',           japanese: '今',               example: '你现在在哪里？',                   notes: '時間' },
      { word: '以前',         reading: 'yǐqián',            japanese: '以前',             example: '以前我住在北京。',                 notes: '時間' },
      { word: '以后',         reading: 'yǐhòu',             japanese: '以後',             example: '以后我想去中国。',                 notes: '時間' },
      { word: '早上',         reading: 'zǎoshang',          japanese: '朝',               example: '我早上六点起床。',                 notes: '時間' },
      { word: '下午',         reading: 'xiàwǔ',             japanese: '午後',             example: '下午我有会议。',                   notes: '時間' },
      { word: '晚上',         reading: 'wǎnshang',          japanese: '夜',               example: '晚上我们一起吃饭吧。',             notes: '時間' },
      { word: '周末',         reading: 'zhōumò',            japanese: '週末',             example: '周末我喜欢去公园。',               notes: '時間' },
      // 交通
      { word: '汽车',         reading: 'qìchē',             japanese: '車',               example: '他开车上班。',                     notes: '交通' },
      { word: '火车',         reading: 'huǒchē',            japanese: '電車',             example: '我坐火车去上海。',                 notes: '交通' },
      { word: '公共汽车',     reading: 'gōnggòng qìchē',    japanese: 'バス',             example: '我每天坐公共汽车上班。',           notes: '交通' },
      { word: '地铁',         reading: 'dìtiě',             japanese: '地下鉄',           example: '北京的地铁很方便。',               notes: '交通' },
      { word: '飞机',         reading: 'fēijī',             japanese: '飛行機',           example: '我们坐飞机去北京。',               notes: '交通' },
      { word: '出租车',       reading: 'chūzūchē',          japanese: 'タクシー',         example: '我叫了一辆出租车。',               notes: '交通' },
      { word: '自行车',       reading: 'zìxíngchē',         japanese: '自転車',           example: '我每天骑自行车上学。',             notes: '交通' },
      { word: '摩托车',       reading: 'mótuōchē',          japanese: 'バイク',           example: '他骑摩托车去工作。',               notes: '交通' },
      // 天気
      { word: '天气',         reading: 'tiānqì',            japanese: '天気',             example: '今天天气怎么样？',                 notes: '天気' },
      { word: '晴天',         reading: 'qíngtiān',          japanese: '晴れ',             example: '今天是晴天，很暖和。',             notes: '天気' },
      { word: '下雨',         reading: 'xià yǔ',            japanese: '雨が降る',         example: '明天可能会下雨。',                 notes: '天気' },
      { word: '下雪',         reading: 'xià xuě',           japanese: '雪が降る',         example: '冬天这里经常下雪。',               notes: '天気' },
      { word: '刮风',         reading: 'guā fēng',          japanese: '風が吹く',         example: '今天风很大。',                     notes: '天気' },
      { word: '温度',         reading: 'wēndù',             japanese: '温度',             example: '今天温度很高。',                   notes: '天気' },
      { word: '季节',         reading: 'jìjié',             japanese: '季節',             example: '我最喜欢春天这个季节。',           notes: '天気' },
      { word: '春',           reading: 'chūn',              japanese: '春',               example: '春天的花很美。',                   notes: '天気' },
      { word: '夏',           reading: 'xià',               japanese: '夏',               example: '夏天很热，我不喜欢。',             notes: '天気' },
      { word: '秋',           reading: 'qiū',               japanese: '秋',               example: '秋天的叶子很漂亮。',               notes: '天気' },
      { word: '冬',           reading: 'dōng',              japanese: '冬',               example: '冬天我喜欢滑雪。',                 notes: '天気' },
      // 感情・状態
      { word: '生气',         reading: 'shēngqì',           japanese: '怒る',             example: '他对我很生气。',                   notes: '感情' },
      { word: '担心',         reading: 'dānxīn',            japanese: '心配する',         example: '妈妈很担心我。',                   notes: '感情' },
      { word: '兴奋',         reading: 'xīngfèn',           japanese: '興奮する',         example: '我对这次旅行很兴奋。',             notes: '感情' },
      { word: '害羞',         reading: 'hàixiū',            japanese: '恥ずかしい',       example: '她见到他就害羞了。',               notes: '感情' },
      { word: '紧张',         reading: 'jǐnzhāng',          japanese: '緊張する',         example: '考试前我很紧张。',                 notes: '感情' },
      { word: '放松',         reading: 'fàngsōng',          japanese: 'リラックスする',   example: '周末我需要放松一下。',             notes: '感情' },
      // 動詞
      { word: '帮助',         reading: 'bāngzhù',           japanese: '手伝う',           example: '谢谢你帮助我。',                   notes: '動詞' },
      { word: '开始',         reading: 'kāishǐ',            japanese: '始める',           example: '我们开始工作吧。',                 notes: '動詞' },
      { word: '结束',         reading: 'jiéshù',            japanese: '終わる',           example: '会议几点结束？',                   notes: '動詞' },
      { word: '准备',         reading: 'zhǔnbèi',           japanese: '準備する',         example: '我在准备考试。',                   notes: '動詞' },
      { word: '决定',         reading: 'juédìng',           japanese: '決める',           example: '我们决定明天出发。',               notes: '動詞' },
      { word: '相信',         reading: 'xiāngxìn',          japanese: '信じる',           example: '我相信你说的话。',                 notes: '動詞' },
      { word: '理解',         reading: 'lǐjiě',             japanese: '理解する',         example: '我不太理解这个问题。',             notes: '動詞' },
      { word: '解决',         reading: 'jiějué',            japanese: '解決する',         example: '我们需要解决这个问题。',           notes: '動詞' },
      { word: '发现',         reading: 'fāxiàn',            japanese: '発見する',         example: '我发现了一个有趣的地方。',         notes: '動詞' },
      { word: '改变',         reading: 'gǎibiàn',           japanese: '変える',           example: '我想改变自己的生活方式。',         notes: '動詞' },
      // 形容詞
      { word: '重要',         reading: 'zhòngyào',          japanese: '重要な',           example: '这件事很重要。',                   notes: '形容詞' },
      { word: '有趣',         reading: 'yǒuqù',             japanese: '面白い',           example: '这本书很有趣。',                   notes: '形容詞' },
      { word: '无聊',         reading: 'wúliáo',            japanese: 'つまらない',       example: '这部电影很无聊。',                 notes: '形容詞' },
      { word: '复杂',         reading: 'fùzá',              japanese: '複雑な',           example: '这个问题很复杂。',                 notes: '形容詞' },
      { word: '简单',         reading: 'jiǎndān',           japanese: '簡単な',           example: '这道题很简单。',                   notes: '形容詞' },
      { word: '困难',         reading: 'kùnnán',            japanese: '困難な',           example: '这件事很困难。',                   notes: '形容詞' },
      { word: '危险',         reading: 'wēixiǎn',           japanese: '危険な',           example: '那个地方很危险。',                 notes: '形容詞' },
      { word: '安全',         reading: 'ānquán',            japanese: '安全な',           example: '这条路走很安全。',                 notes: '形容詞' },
      { word: '健康',         reading: 'jiànkāng',          japanese: '健康な',           example: '我希望你身体健康。',               notes: '形容詞' },
      { word: '聪明',         reading: 'cōngmíng',          japanese: '賢い',             example: '她是一个聪明的学生。',             notes: '形容詞' },
      // 追加単語
      { word: '漂亮',         reading: 'piàoliang',         japanese: '綺麗な・美しい',   example: '这朵花很漂亮。',                   notes: '形容詞' },
      { word: '努力',         reading: 'nǔlì',              japanese: '努力する',         example: '我们要努力学习。',                 notes: '動詞' },
      { word: '成功',         reading: 'chénggōng',         japanese: '成功する',         example: '他的事业很成功。',                 notes: '動詞' },
      { word: '失败',         reading: 'shībài',            japanese: '失敗する',         example: '失败是成功的基础。',               notes: '動詞' },
      { word: '练习',         reading: 'liànxí',            japanese: '練習する',         example: '我每天练习写汉字。',               notes: '動詞' },
      { word: '记住',         reading: 'jìzhù',             japanese: '覚える・記憶する', example: '请记住这个单词。',                 notes: '動詞' },
      { word: '忘记',         reading: 'wàngjì',            japanese: '忘れる',           example: '我忘记带钥匙了。',                 notes: '動詞' },
      { word: '旅行',         reading: 'lǚxíng',            japanese: '旅行する',         example: '我喜欢旅行。',                     notes: '動詞' },
      { word: '购物',         reading: 'gòuwù',             japanese: '買い物する',       example: '周末我们去购物。',                 notes: '動詞' },
      { word: '介绍',         reading: 'jièshào',           japanese: '紹介する',         example: '请介绍一下你自己。',               notes: '動詞' },
      { word: '联系',         reading: 'liánxì',            japanese: '連絡する',         example: '有问题请联系我。',                 notes: '動詞' },
      { word: '回答',         reading: 'huídá',             japanese: '答える',           example: '请回答我的问题。',                 notes: '動詞' },
      { word: '提问',         reading: 'tíwèn',             japanese: '質問する',         example: '有不懂的可以提问。',               notes: '動詞' },
      { word: '参加',         reading: 'cānjiā',            japanese: '参加する',         example: '你参加这次活动吗？',               notes: '動詞' },
      { word: '注意',         reading: 'zhùyì',             japanese: '注意する',         example: '请注意安全。',                     notes: '動詞' },
      { word: '需要',         reading: 'xūyào',             japanese: '必要だ・必要とする', example: '我需要你的帮助。',               notes: '動詞' },
      { word: '可以',         reading: 'kěyǐ',              japanese: 'できる・してもよい', example: '我可以帮你吗？',                 notes: '助動詞' },
      { word: '应该',         reading: 'yīnggāi',           japanese: '〜すべきだ',       example: '你应该多休息。',                   notes: '助動詞' },
      { word: '一起',         reading: 'yīqǐ',              japanese: '一緒に',           example: '我们一起去吧。',                   notes: '副詞' },
      { word: '非常',         reading: 'fēicháng',          japanese: 'とても・非常に',   example: '这道菜非常好吃。',                 notes: '副詞' },
      { word: '已经',         reading: 'yǐjīng',            japanese: 'すでに・もう',     example: '我已经吃过了。',                   notes: '副詞' },
      { word: '还是',         reading: 'háishì',            japanese: 'それとも・やはり', example: '你喝茶还是咖啡？',                 notes: '接続詞' },
      { word: '但是',         reading: 'dànshì',            japanese: 'しかし',           example: '我想去，但是没有时间。',           notes: '接続詞' },
      { word: '所以',         reading: 'suǒyǐ',             japanese: 'だから',           example: '下雨了，所以我没出去。',           notes: '接続詞' },
    ]
  },

  advanced: {
    label: '上級レベル',
    description: '上級・ビジネス単語（約100語）',
    color: '#991b1b',
    words: [
      // ビジネス
      { word: '合同',         reading: 'hétong',            japanese: '契約',             example: '我们签署了合同。',                 notes: 'ビジネス' },
      { word: '谈判',         reading: 'tánpàn',            japanese: '交渉',             example: '双方进行了谈判。',                 notes: 'ビジネス' },
      { word: '投资',         reading: 'tóuzī',             japanese: '投資',             example: '他投资了房地产。',                 notes: 'ビジネス' },
      { word: '利润',         reading: 'lìrùn',             japanese: '利益',             example: '公司今年利润很高。',               notes: 'ビジネス' },
      { word: '市场',         reading: 'shìchǎng',          japanese: '市場',             example: '这个产品在市场上很受欢迎。',       notes: 'ビジネス' },
      { word: '竞争',         reading: 'jìngzhēng',         japanese: '競争',             example: '市场竞争越来越激烈。',             notes: 'ビジネス' },
      { word: '发展',         reading: 'fāzhǎn',            japanese: '発展',             example: '公司发展得很好。',                 notes: 'ビジネス' },
      { word: '管理',         reading: 'guǎnlǐ',            japanese: '管理',             example: '他负责公司的管理工作。',           notes: 'ビジネス' },
      { word: '策略',         reading: 'cèlüè',             japanese: '戦略',             example: '我们需要制定新的策略。',           notes: 'ビジネス' },
      { word: '效率',         reading: 'xiàolǜ',            japanese: '効率',             example: '提高工作效率很重要。',             notes: 'ビジネス' },
      // 社会
      { word: '社会',         reading: 'shèhuì',            japanese: '社会',             example: '我们要为社会做贡献。',             notes: '社会' },
      { word: '政府',         reading: 'zhèngfǔ',           japanese: '政府',             example: '政府出台了新政策。',               notes: '社会' },
      { word: '经济',         reading: 'jīngjì',            japanese: '経済',             example: '中国经济发展很快。',               notes: '社会' },
      { word: '文化',         reading: 'wénhuà',            japanese: '文化',             example: '中国有悠久的文化历史。',           notes: '社会' },
      { word: '教育',         reading: 'jiàoyù',            japanese: '教育',             example: '教育是国家发展的基础。',           notes: '社会' },
      { word: '环境',         reading: 'huánjìng',          japanese: '環境',             example: '我们要保护环境。',                 notes: '社会' },
      { word: '科技',         reading: 'kējì',              japanese: '科学技術',         example: '科技改变了我们的生活。',           notes: '社会' },
      { word: '医疗',         reading: 'yīliáo',            japanese: '医療',             example: '这个国家的医疗水平很高。',         notes: '社会' },
      { word: '法律',         reading: 'fǎlǜ',              japanese: '法律',             example: '我们要遵守法律。',                 notes: '社会' },
      { word: '政策',         reading: 'zhèngcè',           japanese: '政策',             example: '政府制定了新政策。',               notes: '社会' },
      // 抽象概念
      { word: '自由',         reading: 'zìyóu',             japanese: '自由',             example: '人人都有追求自由的权利。',         notes: '抽象概念' },
      { word: '平等',         reading: 'píngděng',          japanese: '平等',             example: '男女平等是重要的原则。',           notes: '抽象概念' },
      { word: '责任',         reading: 'zérèn',             japanese: '責任',             example: '我们要对自己的行为负责任。',       notes: '抽象概念' },
      { word: '义务',         reading: 'yìwù',              japanese: '義務',             example: '纳税是公民的义务。',               notes: '抽象概念' },
      { word: '权利',         reading: 'quánlì',            japanese: '権利',             example: '每个人都有受教育的权利。',         notes: '抽象概念' },
      { word: '道德',         reading: 'dàodé',             japanese: '道徳',             example: '道德是做人的基本准则。',           notes: '抽象概念' },
      { word: '价值',         reading: 'jiàzhí',            japanese: '価値',             example: '这件事对我来说很有价值。',         notes: '抽象概念' },
      { word: '意义',         reading: 'yìyì',              japanese: '意味・意義',       example: '生命的意义在于奉献。',             notes: '抽象概念' },
      { word: '目标',         reading: 'mùbiāo',            japanese: '目標',             example: '我的目标是成为一名医生。',         notes: '抽象概念' },
      { word: '理想',         reading: 'lǐxiǎng',           japanese: '理想',             example: '每个人都有自己的理想。',           notes: '抽象概念' },
      // 高度動詞
      { word: '实现',         reading: 'shíxiàn',           japanese: '実現する',         example: '我终于实现了自己的梦想。',         notes: '高度動詞' },
      { word: '创造',         reading: 'chuàngzào',         japanese: '創造する',         example: '科技创造了新的工作机会。',         notes: '高度動詞' },
      { word: '分析',         reading: 'fēnxī',             japanese: '分析する',         example: '我们需要仔细分析这个问题。',       notes: '高度動詞' },
      { word: '评估',         reading: 'pínggū',            japanese: '評価する',         example: '我们要对结果进行评估。',           notes: '高度動詞' },
      { word: '协调',         reading: 'xiétiáo',           japanese: '調整する',         example: '需要协调各部门的工作。',           notes: '高度動詞' },
      { word: '促进',         reading: 'cùjìn',             japanese: '促進する',         example: '这个政策促进了经济发展。',         notes: '高度動詞' },
      { word: '影响',         reading: 'yǐngxiǎng',         japanese: '影響する',         example: '天气会影响我们的计划。',           notes: '高度動詞' },
      { word: '导致',         reading: 'dǎozhì',            japanese: '引き起こす',       example: '不注意可能导致严重事故。',         notes: '高度動詞' },
      { word: '依赖',         reading: 'yīlài',             japanese: '依存する',         example: '现代人越来越依赖手机。',           notes: '高度動詞' },
      { word: '超越',         reading: 'chāoyuè',           japanese: '超える',           example: '他的成绩超越了所有人。',           notes: '高度動詞' },
      // 学術・科学
      { word: '研究',         reading: 'yánjiū',            japanese: '研究',             example: '科学家们在研究新药物。',           notes: '学術' },
      { word: '实验',         reading: 'shíyàn',            japanese: '実験',             example: '这个实验取得了成功。',             notes: '学術' },
      { word: '数据',         reading: 'shùjù',             japanese: 'データ',           example: '我们需要更多的数据来支持结论。',   notes: '学術' },
      { word: '理论',         reading: 'lǐlùn',             japanese: '理論',             example: '这个理论已被证实。',               notes: '学術' },
      { word: '假设',         reading: 'jiǎshè',            japanese: '仮説',             example: '研究人员提出了新的假设。',         notes: '学術' },
      { word: '结论',         reading: 'jiélùn',            japanese: '結論',             example: '根据实验，我们得出了结论。',       notes: '学術' },
      { word: '证明',         reading: 'zhèngmíng',         japanese: '証明',             example: '他证明了这个定理。',               notes: '学術' },
      { word: '观察',         reading: 'guānchá',           japanese: '観察',             example: '科学家观察了几年。',               notes: '学術' },
      { word: '分类',         reading: 'fēnlèi',            japanese: '分類',             example: '生物学家对动物进行了分类。',       notes: '学術' },
      { word: '统计',         reading: 'tǒngjì',            japanese: '統計',             example: '统计数字表明经济在增长。',         notes: '学術' },
      // 追加ビジネス・高度語彙
      { word: '创新',         reading: 'chuàngxīn',         japanese: 'イノベーション・革新', example: '创新是企业发展的动力。',       notes: 'ビジネス' },
      { word: '合作',         reading: 'hézuò',             japanese: '協力・協働',       example: '双方决定开展合作。',               notes: 'ビジネス' },
      { word: '品质',         reading: 'pǐnzhì',            japanese: '品質',             example: '我们注重产品品质。',               notes: 'ビジネス' },
      { word: '规模',         reading: 'guīmó',             japanese: '規模',             example: '这家公司规模很大。',               notes: 'ビジネス' },
      { word: '机会',         reading: 'jīhuì',             japanese: '機会・チャンス',   example: '这是一个难得的机会。',             notes: 'ビジネス' },
      { word: '挑战',         reading: 'tiǎozhàn',          japanese: '挑戦',             example: '这项工作充满挑战。',               notes: 'ビジネス' },
      { word: '风险',         reading: 'fēngxiǎn',          japanese: 'リスク',           example: '投资有一定的风险。',               notes: 'ビジネス' },
      { word: '预算',         reading: 'yùsuàn',            japanese: '予算',             example: '项目的预算已经确定。',             notes: 'ビジネス' },
      { word: '资源',         reading: 'zīyuán',            japanese: '資源',             example: '我们要合理利用资源。',             notes: '社会' },
      { word: '传统',         reading: 'chuántǒng',         japanese: '伝統',             example: '中国有很多传统节日。',             notes: '文化' },
      { word: '现代',         reading: 'xiàndài',           japanese: '現代',             example: '现代科技发展很快。',               notes: '文化' },
      { word: '交流',         reading: 'jiāoliú',           japanese: '交流',             example: '文化交流促进了理解。',             notes: '社会' },
      { word: '保护',         reading: 'bǎohù',             japanese: '保護する',         example: '我们要保护自然环境。',             notes: '高度動詞' },
      { word: '建立',         reading: 'jiànlì',            japanese: '建立する・設立する', example: '我们建立了新的合作关系。',       notes: '高度動詞' },
      { word: '维持',         reading: 'wéichí',            japanese: '維持する',         example: '我们要维持良好的关系。',           notes: '高度動詞' },
      { word: '提高',         reading: 'tígāo',             japanese: '向上させる・高める', example: '我想提高我的中文水平。',         notes: '高度動詞' },
      { word: '降低',         reading: 'jiàngdī',           japanese: '下げる・低下させる', example: '我们要降低成本。',               notes: '高度動詞' },
      { word: '扩大',         reading: 'kuòdà',             japanese: '拡大する',         example: '公司计划扩大生产规模。',           notes: '高度動詞' },
      { word: '减少',         reading: 'jiǎnshǎo',          japanese: '減らす',           example: '我们要减少浪费。',                 notes: '高度動詞' },
      { word: '增加',         reading: 'zēngjiā',           japanese: '増やす・増加する', example: '今年的销售额大幅增加。',           notes: '高度動詞' },
      { word: '支持',         reading: 'zhīchí',            japanese: '支持する・支援する', example: '感谢大家的支持。',               notes: '高度動詞' },
      { word: '反对',         reading: 'fǎnduì',            japanese: '反対する',         example: '他对这个计划表示反对。',           notes: '高度動詞' },
      { word: '解释',         reading: 'jiěshì',            japanese: '説明する',         example: '请解释一下这个现象。',             notes: '高度動詞' },
      { word: '描述',         reading: 'miáoshù',           japanese: '描写する',         example: '请描述一下你看到的情况。',         notes: '高度動詞' },
      { word: '比较',         reading: 'bǐjiào',            japanese: '比較する',         example: '我们来比较两种方案。',             notes: '高度動詞' },
      { word: '总结',         reading: 'zǒngjié',           japanese: 'まとめる・総括する', example: '请总结一下今天的内容。',         notes: '高度動詞' },
      { word: '预测',         reading: 'yùcè',              japanese: '予測する',         example: '很难预测未来的发展。',             notes: '高度動詞' },
      { word: '确认',         reading: 'quèrèn',            japanese: '確認する',         example: '请确认一下时间和地点。',           notes: '高度動詞' },
      { word: '承担',         reading: 'chéngdān',          japanese: '担う・負担する',   example: '他承担了所有的责任。',             notes: '高度動詞' },
      { word: '克服',         reading: 'kèfú',              japanese: '克服する',         example: '我们要克服困难。',                 notes: '高度動詞' },
    ]
  }
};
