/* ===================================================
   フランス語学習アプリ  words-data.js
   =================================================== */

const WORD_SETS = {
  beginner: {
    label: '初級レベル',
    description: '日常会話の基本単語（約100語）',
    color: '#7c3aed',
    words: [
      // 挨拶
      { word: 'bonjour', japanese: 'こんにちは', example: 'Bonjour! Comment allez-vous?', notes: '挨拶' },
      { word: 'bonsoir', japanese: 'こんばんは', example: 'Bonsoir, madame.', notes: '挨拶' },
      { word: 'bonne nuit', japanese: 'おやすみ', example: 'Bonne nuit, dormez bien!', notes: '挨拶' },
      { word: 'au revoir', japanese: 'さようなら', example: 'Au revoir! À bientôt!', notes: '挨拶' },
      { word: 'merci', japanese: 'ありがとう', example: 'Merci pour votre aide.', notes: '挨拶' },
      { word: 'merci beaucoup', japanese: 'どうもありがとう', example: 'Merci beaucoup pour tout!', notes: '挨拶' },
      { word: "s'il vous plaît", japanese: 'お願いします', example: "De l'eau, s'il vous plaît.", notes: '挨拶' },
      { word: 'excusez-moi', japanese: 'すみません', example: 'Excusez-moi, où est la gare?', notes: '挨拶' },
      { word: 'pardon', japanese: 'ごめんなさい', example: 'Pardon, je suis désolé.', notes: '挨拶' },
      { word: 'de rien', japanese: 'どういたしまして', example: 'Merci! — De rien!', notes: '挨拶' },
      { word: 'oui', japanese: 'はい', example: 'Oui, je comprends.', notes: '挨拶' },
      { word: 'non', japanese: 'いいえ', example: 'Non, merci.', notes: '挨拶' },
      { word: 'peut-être', japanese: 'たぶん', example: 'Peut-être demain.', notes: '挨拶' },
      { word: 'bien sûr', japanese: 'もちろん', example: 'Bien sûr, avec plaisir!', notes: '挨拶' },
      // 人称
      { word: 'je', japanese: '私', example: 'Je suis étudiant.', notes: '人称' },
      { word: 'tu', japanese: 'あなた', example: 'Tu parles français?', notes: '人称' },
      { word: 'il', japanese: '彼', example: 'Il habite à Paris.', notes: '人称' },
      { word: 'elle', japanese: '彼女', example: 'Elle est médecin.', notes: '人称' },
      { word: 'nous', japanese: '私たち', example: 'Nous allons au restaurant.', notes: '人称' },
      { word: 'vous', japanese: 'あなたたち・敬語', example: 'Vous parlez très bien français.', notes: '人称' },
      { word: 'ils', japanese: '彼ら', example: 'Ils sont amis.', notes: '人称' },
      { word: 'elles', japanese: '彼女たち', example: 'Elles travaillent ensemble.', notes: '人称' },
      { word: 'ça', japanese: 'それ', example: 'Ça va bien, merci.', notes: '人称' },
      { word: 'qui', japanese: '誰', example: 'Qui est là?', notes: '人称' },
      // 基本動詞
      { word: 'être', japanese: '〜である', example: 'Je suis content.', notes: '基本動詞' },
      { word: 'avoir', japanese: '持っている', example: "J'ai un chat.", notes: '基本動詞' },
      { word: 'aller', japanese: '行く', example: "Je vais à l'école.", notes: '基本動詞' },
      { word: 'venir', japanese: '来る', example: 'Il vient demain.', notes: '基本動詞' },
      { word: 'faire', japanese: 'する・作る', example: 'Je fais la cuisine.', notes: '基本動詞' },
      { word: 'dire', japanese: '言う', example: 'Qu\'est-ce qu\'il dit?', notes: '基本動詞' },
      { word: 'voir', japanese: '見る', example: 'Je vois la tour Eiffel.', notes: '基本動詞' },
      { word: 'savoir', japanese: '知っている', example: 'Je sais parler français.', notes: '基本動詞' },
      { word: 'pouvoir', japanese: 'できる', example: 'Je peux t\'aider.', notes: '基本動詞' },
      { word: 'vouloir', japanese: '欲しい・したい', example: 'Je veux un café.', notes: '基本動詞' },
      { word: 'devoir', japanese: '〜しなければならない', example: 'Je dois partir maintenant.', notes: '基本動詞' },
      { word: 'manger', japanese: '食べる', example: 'Je mange une pomme.', notes: '基本動詞' },
      { word: 'boire', japanese: '飲む', example: 'Il boit du café.', notes: '基本動詞' },
      { word: 'dormir', japanese: '眠る', example: 'Je dors huit heures par nuit.', notes: '基本動詞' },
      { word: 'parler', japanese: '話す', example: 'Elle parle espagnol.', notes: '基本動詞' },
      { word: 'écouter', japanese: '聴く', example: "J'écoute de la musique.", notes: '基本動詞' },
      { word: 'lire', japanese: '読む', example: 'Je lis un livre.', notes: '基本動詞' },
      { word: 'écrire', japanese: '書く', example: "J'écris une lettre.", notes: '基本動詞' },
      { word: 'apprendre', japanese: '学ぶ', example: "J'apprends le français.", notes: '基本動詞' },
      { word: 'aimer', japanese: '好きだ・愛する', example: "J'aime le chocolat.", notes: '基本動詞' },
      // 家族
      { word: 'famille', japanese: '家族', example: 'Ma famille est grande.', notes: '家族' },
      { word: 'père', japanese: '父', example: 'Mon père est médecin.', notes: '家族' },
      { word: 'mère', japanese: '母', example: 'Ma mère cuisine bien.', notes: '家族' },
      { word: 'frère', japanese: '兄・弟', example: 'Mon frère est plus jeune.', notes: '家族' },
      { word: 'sœur', japanese: '姉・妹', example: 'Ma sœur habite à Lyon.', notes: '家族' },
      { word: 'enfant', japanese: '子供', example: "L'enfant joue dans le parc.", notes: '家族' },
      { word: 'mari', japanese: '夫', example: 'Mon mari travaille à Paris.', notes: '家族' },
      { word: 'femme', japanese: '妻・女性', example: 'Sa femme est professeure.', notes: '家族' },
      { word: 'ami', japanese: '友達', example: 'Il est mon meilleur ami.', notes: '家族' },
      { word: 'collègue', japanese: '同僚', example: 'Ma collègue est sympa.', notes: '家族' },
      // 場所
      { word: 'école', japanese: '学校', example: "Je vais à l'école le matin.", notes: '場所' },
      { word: 'maison', japanese: '家', example: 'Je rentre à la maison.', notes: '場所' },
      { word: 'bureau', japanese: 'オフィス', example: 'Il travaille au bureau.', notes: '場所' },
      { word: 'hôpital', japanese: '病院', example: "Elle travaille à l'hôpital.", notes: '場所' },
      { word: 'banque', japanese: '銀行', example: 'Je vais à la banque.', notes: '場所' },
      { word: 'supermarché', japanese: 'スーパー', example: "J'achète des légumes au supermarché.", notes: '場所' },
      { word: 'restaurant', japanese: 'レストラン', example: 'Nous dînons au restaurant.', notes: '場所' },
      { word: 'bibliothèque', japanese: '図書館', example: 'Je lis à la bibliothèque.', notes: '場所' },
      { word: 'parc', japanese: '公園', example: "Je me promène dans le parc.", notes: '場所' },
      { word: 'gare', japanese: '駅', example: 'Le train part de la gare.', notes: '場所' },
      { word: 'aéroport', japanese: '空港', example: "L'avion arrive à l'aéroport.", notes: '場所' },
      { word: 'hôtel', japanese: 'ホテル', example: 'Nous dormons à l\'hôtel.', notes: '場所' },
      // 食べ物
      { word: 'riz', japanese: '米', example: 'Je mange du riz.', notes: '食べ物' },
      { word: 'pain', japanese: 'パン', example: "J'achète du pain à la boulangerie.", notes: '食べ物' },
      { word: 'fromage', japanese: 'チーズ', example: 'Le fromage français est délicieux.', notes: '食べ物' },
      { word: 'vin', japanese: 'ワイン', example: 'Nous buvons du vin rouge.', notes: '食べ物' },
      { word: 'eau', japanese: '水', example: "Je bois de l'eau chaque matin.", notes: '食べ物' },
      { word: 'café', japanese: 'コーヒー', example: 'Je prends un café le matin.', notes: '食べ物' },
      { word: 'thé', japanese: 'お茶', example: 'Elle boit du thé vert.', notes: '食べ物' },
      { word: 'viande', japanese: '肉', example: 'Je mange de la viande.', notes: '食べ物' },
      { word: 'poisson', japanese: '魚', example: 'Le poisson est frais.', notes: '食べ物' },
      { word: 'légume', japanese: '野菜', example: 'Je mange des légumes chaque jour.', notes: '食べ物' },
      { word: 'fruit', japanese: '果物', example: 'Je mange un fruit après le repas.', notes: '食べ物' },
      { word: 'dessert', japanese: 'デザート', example: 'Nous prenons un dessert.', notes: '食べ物' },
      // 数字
      { word: 'un', japanese: '1', example: "J'ai un chien.", notes: '数字' },
      { word: 'deux', japanese: '2', example: 'Il a deux enfants.', notes: '数字' },
      { word: 'trois', japanese: '3', example: 'Nous sommes trois amis.', notes: '数字' },
      { word: 'quatre', japanese: '4', example: 'Il y a quatre saisons.', notes: '数字' },
      { word: 'cinq', japanese: '5', example: 'Je travaille cinq jours par semaine.', notes: '数字' },
      { word: 'six', japanese: '6', example: 'Il est six heures du matin.', notes: '数字' },
      { word: 'sept', japanese: '7', example: 'La semaine a sept jours.', notes: '数字' },
      { word: 'huit', japanese: '8', example: "J'ai huit cousins.", notes: '数字' },
      { word: 'neuf', japanese: '9', example: 'Elle a neuf ans.', notes: '数字' },
      { word: 'dix', japanese: '10', example: 'Dix élèves sont présents.', notes: '数字' },
      { word: 'cent', japanese: '百', example: 'Il y a cent personnes.', notes: '数字' },
      { word: 'mille', japanese: '千', example: 'Mille mercis!', notes: '数字' },
      // 時間
      { word: "aujourd'hui", japanese: '今日', example: "Aujourd'hui il fait beau.", notes: '時間' },
      { word: 'demain', japanese: '明日', example: 'Je pars demain matin.', notes: '時間' },
      { word: 'hier', japanese: '昨日', example: "Hier, j'ai vu un film.", notes: '時間' },
      { word: 'maintenant', japanese: '今', example: 'Je travaille maintenant.', notes: '時間' },
      { word: 'matin', japanese: '朝', example: 'Je me lève tôt le matin.', notes: '時間' },
      { word: 'après-midi', japanese: '午後', example: "Je dors l'après-midi.", notes: '時間' },
      { word: 'soir', japanese: '夜', example: 'Le soir, je lis un livre.', notes: '時間' },
      { word: 'semaine', japanese: '週', example: 'La semaine prochaine.', notes: '時間' },
      { word: 'mois', japanese: '月', example: 'Ce mois-ci est janvier.', notes: '時間' },
      { word: 'an', japanese: '年', example: "J'ai vingt ans.", notes: '時間' },
      // 形容詞
      { word: 'grand', japanese: '大きい', example: 'Il habite dans une grande maison.', notes: '形容詞' },
      { word: 'petit', japanese: '小さい', example: "J'ai un petit chat.", notes: '形容詞' },
      { word: 'beau', japanese: '美しい', example: 'Il fait beau temps.', notes: '形容詞' },
      { word: 'nouveau', japanese: '新しい', example: "J'ai un nouveau téléphone.", notes: '形容詞' },
      { word: 'vieux', japanese: '古い', example: 'Ce bâtiment est très vieux.', notes: '形容詞' },
      { word: 'bon', japanese: '良い', example: 'Ce repas est très bon.', notes: '形容詞' },
      { word: 'mauvais', japanese: '悪い', example: 'Il fait mauvais temps.', notes: '形容詞' },
      { word: 'cher', japanese: '高い', example: 'Ce restaurant est trop cher.', notes: '形容詞' },
      { word: 'pas cher', japanese: '安い', example: 'Ce vêtement est pas cher.', notes: '形容詞' },
      { word: 'rapide', japanese: '速い', example: 'Le train est rapide.', notes: '形容詞' },
      { word: 'lent', japanese: '遅い', example: 'Cette voiture est lente.', notes: '形容詞' },
      { word: 'heureux', japanese: '幸せ', example: 'Je suis heureux de te voir.', notes: '形容詞' },
      { word: 'triste', japanese: '悲しい', example: 'Elle est triste aujourd\'hui.', notes: '形容詞' },
      { word: 'fatigué', japanese: '疲れた', example: 'Je suis très fatigué.', notes: '形容詞' },
      { word: 'occupé', japanese: '忙しい', example: 'Je suis occupé ce soir.', notes: '形容詞' },
      { word: 'chaud', japanese: '暑い', example: "Il fait chaud en été.", notes: '形容詞' },
      { word: 'froid', japanese: '寒い', example: "Il fait froid en hiver.", notes: '形容詞' },
      // 色
      { word: 'rouge', japanese: '赤', example: 'Elle porte une robe rouge.', notes: '色' },
      { word: 'bleu', japanese: '青', example: 'Le ciel est bleu.', notes: '色' },
      { word: 'vert', japanese: '緑', example: 'Les feuilles sont vertes.', notes: '色' },
      { word: 'jaune', japanese: '黄', example: 'Le soleil est jaune.', notes: '色' },
      { word: 'blanc', japanese: '白', example: 'La neige est blanche.', notes: '色' },
      { word: 'noir', japanese: '黒', example: 'Son chat est noir.', notes: '色' },
      { word: 'rose', japanese: 'ピンク', example: 'Elle aime le rose.', notes: '色' },
      { word: 'violet', japanese: '紫', example: 'Les lavandes sont violettes.', notes: '色' },
      { word: 'orange', japanese: 'オレンジ', example: 'La carotte est orange.', notes: '色' },
      { word: 'gris', japanese: 'グレー', example: 'Le ciel est gris.', notes: '色' },
      // 曜日
      { word: 'lundi', japanese: '月曜日', example: 'Je travaille le lundi.', notes: '曜日' },
      { word: 'mardi', japanese: '火曜日', example: 'Le cours est le mardi.', notes: '曜日' },
      { word: 'mercredi', japanese: '水曜日', example: 'Les enfants ont congé le mercredi.', notes: '曜日' },
      { word: 'jeudi', japanese: '木曜日', example: 'La réunion est jeudi.', notes: '曜日' },
      { word: 'vendredi', japanese: '金曜日', example: 'Le vendredi soir, je sors.', notes: '曜日' },
      { word: 'samedi', japanese: '土曜日', example: 'Je me repose le samedi.', notes: '曜日' },
      { word: 'dimanche', japanese: '日曜日', example: 'Le dimanche, je vais à l\'église.', notes: '曜日' },
    ],
  },
  intermediate: {
    label: '中級レベル',
    description: '中級会話の単語（約100語）',
    color: '#6d28d9',
    words: [
      // 職業
      { word: 'professeur', japanese: '先生', example: 'Mon professeur est très pédagogue.', notes: '職業' },
      { word: 'médecin', japanese: '医者', example: 'Le médecin examine le patient.', notes: '職業' },
      { word: 'ingénieur', japanese: 'エンジニア', example: "L'ingénieur conçoit des ponts.", notes: '職業' },
      { word: 'avocat', japanese: '弁護士', example: "L'avocat défend son client.", notes: '職業' },
      { word: 'infirmier', japanese: '看護師', example: "L'infirmier soigne les patients.", notes: '職業' },
      { word: 'chauffeur', japanese: '運転手', example: 'Le chauffeur conduit prudemment.', notes: '職業' },
      { word: 'cuisinier', japanese: '料理人', example: 'Le cuisinier prépare un plat délicieux.', notes: '職業' },
      { word: 'journaliste', japanese: '記者', example: 'La journaliste écrit un article.', notes: '職業' },
      { word: 'policier', japanese: '警察', example: 'Le policier patrouille dans la rue.', notes: '職業' },
      { word: "homme d'affaires", japanese: 'ビジネスマン', example: "L'homme d'affaires négocie un contrat.", notes: '職業' },
      // 交通
      { word: 'voiture', japanese: '車', example: 'Je vais au travail en voiture.', notes: '交通' },
      { word: 'train', japanese: '電車', example: 'Le train arrive à midi.', notes: '交通' },
      { word: 'bus', japanese: 'バス', example: 'Je prends le bus chaque matin.', notes: '交通' },
      { word: 'métro', japanese: '地下鉄', example: 'Le métro parisien est rapide.', notes: '交通' },
      { word: 'avion', japanese: '飛行機', example: "L'avion décolle à dix heures.", notes: '交通' },
      { word: 'taxi', japanese: 'タクシー', example: 'Je prends un taxi pour aller à l\'aéroport.', notes: '交通' },
      { word: 'vélo', japanese: '自転車', example: 'Je fais du vélo le week-end.', notes: '交通' },
      { word: 'bateau', japanese: '船', example: 'Le bateau traverse la mer.', notes: '交通' },
      // 感情
      { word: 'content', japanese: '嬉しい', example: 'Je suis content de te voir!', notes: '感情' },
      { word: 'en colère', japanese: '怒っている', example: 'Il est en colère contre moi.', notes: '感情' },
      { word: 'inquiet', japanese: '心配している', example: 'Je suis inquiet pour toi.', notes: '感情' },
      { word: 'excité', japanese: '興奮している', example: 'Les enfants sont excités.', notes: '感情' },
      { word: 'honteux', japanese: '恥ずかしい', example: 'Il est honteux de son erreur.', notes: '感情' },
      { word: 'nerveux', japanese: '緊張している', example: 'Je suis nerveux avant l\'examen.', notes: '感情' },
      { word: 'détendu', japanese: 'リラックスした', example: 'Je me sens détendu en vacances.', notes: '感情' },
      { word: 'surpris', japanese: '驚いた', example: 'Je suis surpris par la nouvelle.', notes: '感情' },
      // 天気
      { word: 'temps', japanese: '天気', example: 'Quel temps fait-il?', notes: '天気' },
      { word: 'soleil', japanese: '太陽・晴れ', example: 'Le soleil brille fort.', notes: '天気' },
      { word: 'pluie', japanese: '雨', example: 'La pluie tombe depuis ce matin.', notes: '天気' },
      { word: 'neige', japanese: '雪', example: 'La neige couvre les montagnes.', notes: '天気' },
      { word: 'vent', japanese: '風', example: 'Il y a beaucoup de vent.', notes: '天気' },
      { word: 'nuage', japanese: '雲', example: 'Les nuages cachent le soleil.', notes: '天気' },
      { word: 'température', japanese: '温度', example: 'La température est de vingt degrés.', notes: '天気' },
      { word: 'saison', japanese: '季節', example: 'Quelle est votre saison préférée?', notes: '天気' },
      { word: 'printemps', japanese: '春', example: 'Les fleurs poussent au printemps.', notes: '天気' },
      { word: 'été', japanese: '夏', example: "Nous partons en vacances l'été.", notes: '天気' },
      { word: 'automne', japanese: '秋', example: 'En automne, les feuilles tombent.', notes: '天気' },
      { word: 'hiver', japanese: '冬', example: "L'hiver est froid cette année.", notes: '天気' },
      // 中級動詞
      { word: 'aider', japanese: '手伝う', example: 'Peux-tu m\'aider s\'il te plaît?', notes: '動詞' },
      { word: 'commencer', japanese: '始める', example: 'Je commence le travail à huit heures.', notes: '動詞' },
      { word: 'finir', japanese: '終える', example: 'Je finis le projet demain.', notes: '動詞' },
      { word: 'préparer', japanese: '準備する', example: 'Je prépare le repas.', notes: '動詞' },
      { word: 'décider', japanese: '決める', example: 'Nous devons décider maintenant.', notes: '動詞' },
      { word: 'croire', japanese: '信じる', example: 'Je crois en toi.', notes: '動詞' },
      { word: 'comprendre', japanese: '理解する', example: 'Je comprends la situation.', notes: '動詞' },
      { word: 'résoudre', japanese: '解決する', example: 'Nous devons résoudre ce problème.', notes: '動詞' },
      { word: 'découvrir', japanese: '発見する', example: 'Il a découvert une nouvelle espèce.', notes: '動詞' },
      { word: 'changer', japanese: '変える', example: 'Il faut changer cette habitude.', notes: '動詞' },
      { word: 'travailler', japanese: '働く', example: 'Je travaille du lundi au vendredi.', notes: '動詞' },
      { word: 'voyager', japanese: '旅行する', example: "J'aime voyager en Europe.", notes: '動詞' },
      { word: 'rencontrer', japanese: '会う・出会う', example: "J'ai rencontré mon ami hier.", notes: '動詞' },
      { word: 'présenter', japanese: '紹介する', example: 'Je vais vous présenter mon collègue.', notes: '動詞' },
      { word: 'expliquer', japanese: '説明する', example: 'Pouvez-vous expliquer ce problème?', notes: '動詞' },
      { word: 'oublier', japanese: '忘れる', example: "N'oublie pas ton rendez-vous!", notes: '動詞' },
      { word: 'chercher', japanese: '探す', example: 'Je cherche mes clés.', notes: '動詞' },
      { word: 'trouver', japanese: '見つける', example: "J'ai trouvé une solution.", notes: '動詞' },
      { word: 'attendre', japanese: '待つ', example: "J'attends le bus.", notes: '動詞' },
      { word: 'répondre', japanese: '答える', example: 'Veuillez répondre à ma question.', notes: '動詞' },
      // 中級形容詞
      { word: 'important', japanese: '重要な', example: "C'est une décision importante.", notes: '形容詞' },
      { word: 'intéressant', japanese: '面白い', example: 'Ce film est très intéressant.', notes: '形容詞' },
      { word: 'ennuyeux', japanese: '退屈な', example: 'Ce cours est ennuyeux.', notes: '形容詞' },
      { word: 'compliqué', japanese: '複雑な', example: 'Cette situation est compliquée.', notes: '形容詞' },
      { word: 'simple', japanese: '簡単な', example: 'La recette est simple.', notes: '形容詞' },
      { word: 'difficile', japanese: '難しい', example: "L'examen est difficile.", notes: '形容詞' },
      { word: 'dangereux', japanese: '危険な', example: 'La route est dangereuse.', notes: '形容詞' },
      { word: 'sûr', japanese: '安全な', example: 'Ce quartier est sûr.', notes: '形容詞' },
      { word: 'sain', japanese: '健康な', example: 'Manger des légumes est sain.', notes: '形容詞' },
      { word: 'intelligent', japanese: '賢い', example: "C'est un enfant intelligent.", notes: '形容詞' },
      // 日常表現
      { word: 'problème', japanese: '問題', example: "Il n'y a pas de problème.", notes: '名詞' },
      { word: 'réponse', japanese: '返事・答え', example: "J'attends ta réponse.", notes: '名詞' },
      { word: 'question', japanese: '質問', example: "J'ai une question à poser.", notes: '名詞' },
      { word: 'idée', japanese: 'アイデア', example: "C'est une bonne idée!", notes: '名詞' },
      { word: 'décision', japanese: '決断', example: "C'est une décision difficile.", notes: '名詞' },
      { word: 'situation', japanese: '状況', example: 'La situation est grave.', notes: '名詞' },
      { word: 'opportunité', japanese: '機会', example: "C'est une belle opportunité.", notes: '名詞' },
      { word: 'résultat', japanese: '結果', example: 'Quel est le résultat?', notes: '名詞' },
      { word: 'raison', japanese: '理由', example: 'Quelle est la raison?', notes: '名詞' },
      { word: 'moyen', japanese: '手段・方法', example: 'Quel est le meilleur moyen?', notes: '名詞' },
      // 副詞・前置詞
      { word: 'souvent', japanese: 'よく・しばしば', example: 'Je vais souvent au cinéma.', notes: '副詞' },
      { word: 'toujours', japanese: 'いつも', example: 'Il est toujours en retard.', notes: '副詞' },
      { word: 'jamais', japanese: '決して〜ない', example: 'Je ne fume jamais.', notes: '副詞' },
      { word: 'parfois', japanese: 'ときどき', example: 'Je lis parfois le soir.', notes: '副詞' },
      { word: 'très', japanese: 'とても', example: 'Il est très gentil.', notes: '副詞' },
      { word: 'assez', japanese: '十分に', example: "J'ai assez mangé.", notes: '副詞' },
      { word: 'ensemble', japanese: '一緒に', example: 'Nous travaillons ensemble.', notes: '副詞' },
      { word: 'rapidement', japanese: 'すばやく', example: 'Il marche rapidement.', notes: '副詞' },
      { word: 'seulement', japanese: 'だけ', example: 'Je veux seulement te parler.', notes: '副詞' },
      { word: 'vraiment', japanese: '本当に', example: 'Je suis vraiment désolé.', notes: '副詞' },
    ],
  },
  advanced: {
    label: '上級レベル',
    description: '上級・ビジネス単語（約100語）',
    color: '#5b21b6',
    words: [
      // ビジネス
      { word: 'contrat', japanese: '契約', example: 'Nous signons le contrat demain.', notes: 'ビジネス' },
      { word: 'négociation', japanese: '交渉', example: 'La négociation est en cours.', notes: 'ビジネス' },
      { word: 'investissement', japanese: '投資', example: "L'investissement est risqué.", notes: 'ビジネス' },
      { word: 'bénéfice', japanese: '利益', example: "L'entreprise réalise un bénéfice.", notes: 'ビジネス' },
      { word: 'marché', japanese: '市場', example: 'Le marché est en croissance.', notes: 'ビジネス' },
      { word: 'concurrence', japanese: '競争', example: 'La concurrence est féroce.', notes: 'ビジネス' },
      { word: 'développement', japanese: '発展', example: 'Le développement durable est essentiel.', notes: 'ビジネス' },
      { word: 'gestion', japanese: '管理', example: 'La gestion des ressources est cruciale.', notes: 'ビジネス' },
      { word: 'stratégie', japanese: '戦略', example: 'Quelle est notre stratégie?', notes: 'ビジネス' },
      { word: 'efficacité', japanese: '効率', example: "L'efficacité de l'équipe est remarquable.", notes: 'ビジネス' },
      { word: 'réunion', japanese: '会議', example: 'La réunion commence à neuf heures.', notes: 'ビジネス' },
      { word: 'budget', japanese: '予算', example: 'Le budget est limité.', notes: 'ビジネス' },
      { word: 'rapport', japanese: 'レポート', example: 'Je rédige un rapport hebdomadaire.', notes: 'ビジネス' },
      { word: 'partenariat', japanese: '提携', example: 'Nous cherchons un partenariat.', notes: 'ビジネス' },
      { word: 'entreprise', japanese: '企業', example: "L'entreprise a mille employés.", notes: 'ビジネス' },
      // 社会
      { word: 'société', japanese: '社会', example: 'La société évolue rapidement.', notes: '社会' },
      { word: 'gouvernement', japanese: '政府', example: 'Le gouvernement annonce une réforme.', notes: '社会' },
      { word: 'économie', japanese: '経済', example: "L'économie mondiale est fragile.", notes: '社会' },
      { word: 'culture', japanese: '文化', example: 'La culture française est riche.', notes: '社会' },
      { word: 'éducation', japanese: '教育', example: "L'éducation est un droit fondamental.", notes: '社会' },
      { word: 'environnement', japanese: '環境', example: "Protéger l'environnement est vital.", notes: '社会' },
      { word: 'technologie', japanese: '科学技術', example: 'La technologie avance vite.', notes: '社会' },
      { word: 'santé', japanese: '健康・医療', example: 'La santé publique est prioritaire.', notes: '社会' },
      { word: 'loi', japanese: '法律', example: 'Il faut respecter la loi.', notes: '社会' },
      { word: 'politique', japanese: '政策・政治', example: 'La politique étrangère est complexe.', notes: '社会' },
      { word: 'citoyenneté', japanese: '市民権', example: 'La citoyenneté implique des devoirs.', notes: '社会' },
      { word: 'démocratie', japanese: '民主主義', example: 'La démocratie garantit la liberté.', notes: '社会' },
      // 抽象概念
      { word: 'liberté', japanese: '自由', example: 'La liberté est un droit fondamental.', notes: '抽象' },
      { word: 'égalité', japanese: '平等', example: "L'égalité est inscrite dans la Constitution.", notes: '抽象' },
      { word: 'responsabilité', japanese: '責任', example: 'Chacun a sa responsabilité.', notes: '抽象' },
      { word: 'devoir', japanese: '義務', example: "C'est mon devoir de citoyen.", notes: '抽象' },
      { word: 'droit', japanese: '権利', example: "J'ai le droit de m'exprimer.", notes: '抽象' },
      { word: 'morale', japanese: '道徳', example: 'La morale guide nos actions.', notes: '抽象' },
      { word: 'valeur', japanese: '価値', example: 'Quelles sont vos valeurs?', notes: '抽象' },
      { word: 'signification', japanese: '意味', example: 'Quelle est la signification de ce mot?', notes: '抽象' },
      { word: 'objectif', japanese: '目標', example: 'Mon objectif est de réussir.', notes: '抽象' },
      { word: 'idéal', japanese: '理想', example: "L'idéal serait de travailler ensemble.", notes: '抽象' },
      { word: 'principe', japanese: '原則', example: 'Je respecte ce principe.', notes: '抽象' },
      { word: 'perspective', japanese: '観点・展望', example: 'Voyons la situation sous une autre perspective.', notes: '抽象' },
      // 高度動詞
      { word: 'réaliser', japanese: '実現する', example: 'Je veux réaliser mon rêve.', notes: '高度動詞' },
      { word: 'créer', japanese: '創造する', example: "L'artiste crée une œuvre magnifique.", notes: '高度動詞' },
      { word: 'analyser', japanese: '分析する', example: 'Il faut analyser les données.', notes: '高度動詞' },
      { word: 'évaluer', japanese: '評価する', example: "Nous devons évaluer les risques.", notes: '高度動詞' },
      { word: 'coordonner', japanese: '調整する', example: 'Il faut coordonner les efforts.', notes: '高度動詞' },
      { word: 'promouvoir', japanese: '促進する', example: 'Nous cherchons à promouvoir la paix.', notes: '高度動詞' },
      { word: 'influencer', japanese: '影響する', example: 'Les médias influencent notre opinion.', notes: '高度動詞' },
      { word: 'transcender', japanese: '超える', example: 'Il faut transcender nos limites.', notes: '高度動詞' },
      { word: 'gérer', japanese: '管理する', example: 'Je dois gérer mon temps.', notes: '高度動詞' },
      { word: 'innover', japanese: '革新する', example: "L'entreprise doit innover pour survivre.", notes: '高度動詞' },
      { word: 'déléguer', japanese: '委任する', example: 'Le chef délègue les tâches.', notes: '高度動詞' },
      { word: 'négocier', japanese: '交渉する', example: 'Nous négocions un accord commercial.', notes: '高度動詞' },
      { word: 'anticiper', japanese: '予測する', example: 'Il faut anticiper les problèmes.', notes: '高度動詞' },
      { word: 'optimiser', japanese: '最適化する', example: 'Comment optimiser ce processus?', notes: '高度動詞' },
      { word: 'intégrer', japanese: '統合する', example: 'Il faut intégrer toutes les parties.', notes: '高度動詞' },
      // 学術
      { word: 'recherche', japanese: '研究', example: 'La recherche scientifique avance.', notes: '学術' },
      { word: 'expérience', japanese: '実験・経験', example: "L'expérience prouve la théorie.", notes: '学術' },
      { word: 'données', japanese: 'データ', example: 'Nous analysons les données.', notes: '学術' },
      { word: 'théorie', japanese: '理論', example: 'La théorie est confirmée.', notes: '学術' },
      { word: 'hypothèse', japanese: '仮説', example: 'Testons cette hypothèse.', notes: '学術' },
      { word: 'conclusion', japanese: '結論', example: 'Quelle est votre conclusion?', notes: '学術' },
      { word: 'démontrer', japanese: '証明する', example: 'Il faut démontrer cette assertion.', notes: '学術' },
      { word: 'observer', japanese: '観察する', example: 'On observe un phénomène intéressant.', notes: '学術' },
      { word: 'classer', japanese: '分類する', example: 'Classons les résultats par catégorie.', notes: '学術' },
      { word: 'statistique', japanese: '統計', example: 'Les statistiques montrent une tendance.', notes: '学術' },
      { word: 'méthodologie', japanese: '方法論', example: 'La méthodologie est rigoureuse.', notes: '学術' },
      { word: 'paradigme', japanese: 'パラダイム', example: 'Un nouveau paradigme émerge.', notes: '学術' },
      // 高度形容詞・表現
      { word: 'ambigu', japanese: 'あいまいな', example: 'Ce message est ambigu.', notes: '形容詞' },
      { word: 'rigoureux', japanese: '厳密な', example: 'Il faut être rigoureux dans ce travail.', notes: '形容詞' },
      { word: 'innovant', japanese: '革新的な', example: "C'est un projet innovant.", notes: '形容詞' },
      { word: 'pertinent', japanese: '適切な', example: 'Votre remarque est pertinente.', notes: '形容詞' },
      { word: 'cohérent', japanese: '一貫した', example: 'Son discours est cohérent.', notes: '形容詞' },
      { word: 'complexe', japanese: '複雑な', example: 'Cette situation est très complexe.', notes: '形容詞' },
      { word: 'durable', japanese: '持続可能な', example: "Le développement durable est l'avenir.", notes: '形容詞' },
      { word: 'fondamental', japanese: '根本的な', example: "C'est un changement fondamental.", notes: '形容詞' },
      { word: 'subtil', japanese: '微妙な', example: 'La différence est subtile.', notes: '形容詞' },
      { word: 'pragmatique', japanese: '実用的な', example: 'Soyons pragmatiques dans notre approche.', notes: '形容詞' },
      // 哲学・文学
      { word: 'conscience', japanese: '意識', example: 'La conscience humaine est complexe.', notes: '哲学' },
      { word: 'existence', japanese: '存在', example: "L'existence précède l'essence.", notes: '哲学' },
      { word: 'authenticité', japanese: '誠実さ・本物性', example: "L'authenticité est une qualité rare.", notes: '哲学' },
      { word: 'contemplation', japanese: '瞑想・熟考', example: 'La contemplation apporte la paix.', notes: '哲学' },
      { word: 'dialectique', japanese: '弁証法', example: 'La dialectique est une méthode de raisonnement.', notes: '哲学' },
      { word: 'nuance', japanese: 'ニュアンス', example: 'Il y a une nuance importante ici.', notes: '哲学' },
      { word: 'récit', japanese: '物語', example: 'Ce récit est poignant.', notes: '文学' },
      { word: 'narratif', japanese: '物語の', example: 'Le style narratif est captivant.', notes: '文学' },
      { word: 'métaphore', japanese: '比喩', example: 'Cette métaphore est bien choisie.', notes: '文学' },
      { word: 'rhétorique', japanese: '修辞学', example: 'La rhétorique est un art.', notes: '文学' },
    ],
  },
};
