/* ============================================================
   無料単語集データ
   中学 / 高校 / 大学レベル
   ============================================================ */

const WORD_SETS = {
  junior: {
    label: '中学レベル',
    description: '中学校英語の基本単語（約100語）',
    color: '#16a34a',
    words: [
      // 基本動詞
      { english: 'eat',       japanese: '食べる',     example: 'I eat breakfast every morning.', notes: '基本動詞' },
      { english: 'drink',     japanese: '飲む',       example: 'She drinks a lot of water.', notes: '基本動詞' },
      { english: 'sleep',     japanese: '眠る',       example: 'I sleep for eight hours.', notes: '基本動詞' },
      { english: 'wake',      japanese: '起きる',     example: 'He wakes up at six.', notes: '基本動詞' },
      { english: 'walk',      japanese: '歩く',       example: 'We walk to school.', notes: '基本動詞' },
      { english: 'run',       japanese: '走る',       example: 'She runs fast.', notes: '基本動詞' },
      { english: 'jump',      japanese: '跳ぶ',       example: 'The cat jumped over the fence.', notes: '基本動詞' },
      { english: 'swim',      japanese: '泳ぐ',       example: 'I swim in the pool every week.', notes: '基本動詞' },
      { english: 'play',      japanese: '遊ぶ・演奏する', example: 'They play soccer after school.', notes: '基本動詞' },
      { english: 'study',     japanese: '勉強する',   example: 'I study English every day.', notes: '基本動詞' },
      { english: 'read',      japanese: '読む',       example: 'He reads books before bed.', notes: '基本動詞' },
      { english: 'write',     japanese: '書く',       example: 'She writes in her diary.', notes: '基本動詞' },
      { english: 'listen',    japanese: '聴く',       example: 'Please listen carefully.', notes: '基本動詞' },
      { english: 'speak',     japanese: '話す',       example: 'Can you speak English?', notes: '基本動詞' },
      { english: 'teach',     japanese: '教える',     example: 'My father teaches math.', notes: '基本動詞' },
      { english: 'learn',     japanese: '学ぶ',       example: 'I want to learn French.', notes: '基本動詞' },
      { english: 'help',      japanese: '助ける',     example: 'Can you help me?', notes: '基本動詞' },
      { english: 'use',       japanese: '使う',       example: 'I use this app every day.', notes: '基本動詞' },
      { english: 'open',      japanese: '開ける',     example: 'Please open the window.', notes: '基本動詞' },
      { english: 'close',     japanese: '閉める',     example: 'Close the door, please.', notes: '基本動詞' },
      // 家族・人
      { english: 'family',    japanese: '家族',       example: 'My family is small.', notes: '家族' },
      { english: 'father',    japanese: '父',         example: 'My father is a doctor.', notes: '家族' },
      { english: 'mother',    japanese: '母',         example: 'My mother cooks dinner.', notes: '家族' },
      { english: 'brother',   japanese: '兄・弟',     example: 'I have one brother.', notes: '家族' },
      { english: 'sister',    japanese: '姉・妹',     example: 'My sister is ten years old.', notes: '家族' },
      { english: 'friend',    japanese: '友達',       example: 'She is my best friend.', notes: '人間関係' },
      { english: 'teacher',   japanese: '先生',       example: 'Our teacher is very kind.', notes: '職業' },
      { english: 'student',   japanese: '生徒・学生', example: 'He is a good student.', notes: '職業' },
      // 形容詞
      { english: 'big',       japanese: '大きい',     example: 'That is a big dog.', notes: '形容詞' },
      { english: 'small',     japanese: '小さい',     example: 'She has a small bag.', notes: '形容詞' },
      { english: 'tall',      japanese: '背が高い',   example: 'He is very tall.', notes: '形容詞' },
      { english: 'short',     japanese: '短い・背が低い', example: 'This skirt is too short.', notes: '形容詞' },
      { english: 'long',      japanese: '長い',       example: 'Her hair is very long.', notes: '形容詞' },
      { english: 'hot',       japanese: '暑い・熱い', example: 'It is very hot today.', notes: '形容詞' },
      { english: 'cold',      japanese: '寒い・冷たい', example: 'The water is cold.', notes: '形容詞' },
      { english: 'new',       japanese: '新しい',     example: 'I have a new phone.', notes: '形容詞' },
      { english: 'old',       japanese: '古い・年をとった', example: 'This house is very old.', notes: '形容詞' },
      { english: 'good',      japanese: '良い',       example: 'This is a good idea.', notes: '形容詞' },
      { english: 'bad',       japanese: '悪い',       example: 'The weather is bad today.', notes: '形容詞' },
      { english: 'beautiful', japanese: '美しい',     example: 'What a beautiful flower!', notes: '形容詞' },
      { english: 'kind',      japanese: '親切な',     example: 'She is very kind to everyone.', notes: '形容詞' },
      { english: 'busy',      japanese: '忙しい',     example: 'I am very busy this week.', notes: '形容詞' },
      { english: 'easy',      japanese: '簡単な',     example: 'This test is easy.', notes: '形容詞' },
      { english: 'difficult', japanese: '難しい',     example: 'Math is difficult for me.', notes: '形容詞' },
      { english: 'free',      japanese: '自由な・暇な', example: 'Are you free tomorrow?', notes: '形容詞' },
      // 場所・建物
      { english: 'school',    japanese: '学校',       example: 'I go to school by bike.', notes: '場所' },
      { english: 'home',      japanese: '家・自宅',   example: 'I stay at home today.', notes: '場所' },
      { english: 'park',      japanese: '公園',       example: 'Children play in the park.', notes: '場所' },
      { english: 'hospital',  japanese: '病院',       example: 'The hospital is near here.', notes: '場所' },
      { english: 'library',   japanese: '図書館',     example: 'I borrow books from the library.', notes: '場所' },
      { english: 'store',     japanese: '店',         example: 'There is a store on the corner.', notes: '場所' },
      { english: 'station',   japanese: '駅',         example: 'The station is five minutes away.', notes: '場所' },
      // 食べ物
      { english: 'rice',      japanese: 'ご飯・米',   example: 'I eat rice every day.', notes: '食べ物' },
      { english: 'bread',     japanese: 'パン',       example: 'I had bread for breakfast.', notes: '食べ物' },
      { english: 'water',     japanese: '水',         example: 'Please drink more water.', notes: '飲み物' },
      { english: 'milk',      japanese: '牛乳',       example: 'She drinks milk every morning.', notes: '飲み物' },
      // 時間・日常
      { english: 'morning',   japanese: '朝',         example: 'I exercise in the morning.', notes: '時間' },
      { english: 'afternoon', japanese: '午後',       example: 'See you this afternoon.', notes: '時間' },
      { english: 'evening',   japanese: '夕方',       example: 'We had dinner in the evening.', notes: '時間' },
      { english: 'night',     japanese: '夜',         example: 'I study at night.', notes: '時間' },
      { english: 'today',     japanese: '今日',       example: 'What day is today?', notes: '時間' },
      { english: 'tomorrow',  japanese: '明日',       example: 'See you tomorrow.', notes: '時間' },
      { english: 'yesterday', japanese: '昨日',       example: 'I was sick yesterday.', notes: '時間' },
      { english: 'week',      japanese: '週',         example: 'I exercise three times a week.', notes: '時間' },
      { english: 'year',      japanese: '年',         example: 'She is ten years old.', notes: '時間' },
      // 自然
      { english: 'weather',   japanese: '天気',       example: 'The weather is nice today.', notes: '自然' },
      { english: 'rain',      japanese: '雨',         example: 'I hope it does not rain.', notes: '自然' },
      { english: 'snow',      japanese: '雪',         example: 'We got a lot of snow.', notes: '自然' },
      { english: 'sun',       japanese: '太陽',       example: 'The sun rises in the east.', notes: '自然' },
      { english: 'sky',       japanese: '空',         example: 'The sky is blue today.', notes: '自然' },
      { english: 'sea',       japanese: '海',         example: 'We swim in the sea.', notes: '自然' },
      { english: 'mountain',  japanese: '山',         example: 'We climbed a high mountain.', notes: '自然' },
      { english: 'flower',    japanese: '花',         example: 'She gave me a beautiful flower.', notes: '植物' },
      { english: 'tree',      japanese: '木',         example: 'There is a big tree in the garden.', notes: '植物' },
      // 色
      { english: 'red',       japanese: '赤',         example: 'She wore a red dress.', notes: '色' },
      { english: 'blue',      japanese: '青',         example: 'The sky is blue.', notes: '色' },
      { english: 'green',     japanese: '緑',         example: 'The leaves are green.', notes: '色' },
      { english: 'yellow',    japanese: '黄色',       example: 'Bananas are yellow.', notes: '色' },
      { english: 'white',     japanese: '白',         example: 'Snow is white.', notes: '色' },
      { english: 'black',     japanese: '黒',         example: 'The cat is black.', notes: '色' },
      { english: 'pink',      japanese: 'ピンク',     example: 'She likes pink flowers.', notes: '色' },
      { english: 'orange',    japanese: 'オレンジ',   example: 'Oranges are orange.', notes: '色' },
      { english: 'brown',     japanese: '茶色',       example: 'The dog has brown fur.', notes: '色' },
      // 教科
      { english: 'math',      japanese: '数学',       example: 'I am good at math.', notes: '教科' },
      { english: 'science',   japanese: '理科・科学', example: 'Science is my favorite subject.', notes: '教科' },
      { english: 'history',   japanese: '歴史',       example: 'I enjoy learning history.', notes: '教科' },
      { english: 'art',       japanese: '美術・芸術', example: 'She is talented in art.', notes: '教科' },
      { english: 'geography', japanese: '地理',       example: 'We study world geography.', notes: '教科' },
      { english: 'language',  japanese: '言語',       example: 'English is a global language.', notes: '教科' },
      // 服・持ち物
      { english: 'shirt',     japanese: 'シャツ',     example: 'He wore a white shirt.', notes: '服' },
      { english: 'hat',       japanese: '帽子',       example: 'Put on your hat.', notes: '服' },
      { english: 'shoes',     japanese: '靴',         example: 'I bought new shoes.', notes: '服' },
      { english: 'bag',       japanese: 'バッグ・鞄', example: 'I carry a school bag.', notes: '持ち物' },
      { english: 'glasses',   japanese: 'メガネ',     example: 'She wears glasses.', notes: '持ち物' },
      { english: 'watch',     japanese: '時計（腕）', example: 'He has a nice watch.', notes: '持ち物' },
      // 体（追加）
      { english: 'leg',       japanese: '脚',         example: 'She hurt her leg.', notes: '体' },
      { english: 'arm',       japanese: '腕',         example: 'He raised his arm.', notes: '体' },
      { english: 'ear',       japanese: '耳',         example: 'She has sharp ears.', notes: '体' },
      { english: 'mouth',     japanese: '口',         example: 'Open your mouth.', notes: '体' },
      { english: 'nose',      japanese: '鼻',         example: 'My nose is cold.', notes: '体' },
      { english: 'back',      japanese: '背中',       example: 'My back hurts.', notes: '体' },
      { english: 'finger',    japanese: '指',         example: 'She cut her finger.', notes: '体' },
      // 数・時間
      { english: 'minute',    japanese: '分',         example: 'Wait five minutes.', notes: '時間' },
      { english: 'hour',      japanese: '時間',       example: 'I studied for two hours.', notes: '時間' },
      { english: 'second',    japanese: '秒',         example: 'Just a second!', notes: '時間' },
      { english: 'hundred',   japanese: '百',         example: 'There are a hundred people.', notes: '数' },
      { english: 'thousand',  japanese: '千',         example: 'A thousand people attended.', notes: '数' },
      // 食べ物（追加）
      { english: 'egg',       japanese: '卵',         example: 'I ate two eggs for breakfast.', notes: '食べ物' },
      { english: 'meat',      japanese: '肉',         example: 'He does not eat meat.', notes: '食べ物' },
      { english: 'fish',      japanese: '魚',         example: 'She loves eating fish.', notes: '食べ物' },
      { english: 'vegetable', japanese: '野菜',       example: 'Eat more vegetables.', notes: '食べ物' },
      { english: 'fruit',     japanese: '果物',       example: 'Fruit is good for your health.', notes: '食べ物' },
      { english: 'sugar',     japanese: '砂糖',       example: 'Do you take sugar in your tea?', notes: '食べ物' },
      { english: 'salt',      japanese: '塩',         example: 'Please pass the salt.', notes: '食べ物' },
      { english: 'soup',      japanese: 'スープ',     example: 'She made vegetable soup.', notes: '食べ物' },
      // 動詞（追加）
      { english: 'buy',       japanese: '買う',       example: 'I need to buy groceries.', notes: '動詞' },
      { english: 'sell',      japanese: '売る',       example: 'They sell fresh vegetables.', notes: '動詞' },
      { english: 'give',      japanese: '与える・あげる', example: 'Give me a hand, please.', notes: '動詞' },
      { english: 'take',      japanese: '取る・持っていく', example: 'Take an umbrella.', notes: '動詞' },
      { english: 'make',      japanese: '作る',       example: 'She made a cake.', notes: '動詞' },
      { english: 'find',      japanese: '見つける',   example: 'I cannot find my keys.', notes: '動詞' },
      { english: 'think',     japanese: '考える・思う', example: 'Think before you speak.', notes: '動詞' },
      { english: 'feel',      japanese: '感じる',     example: 'How do you feel today?', notes: '動詞' },
      { english: 'remember',  japanese: '覚えている・思い出す', example: 'Remember to call me.', notes: '動詞' },
      { english: 'forget',    japanese: '忘れる',     example: 'Don\'t forget your homework.', notes: '動詞' },
      { english: 'try',       japanese: '試みる・努力する', example: 'Try your best!', notes: '動詞' },
      { english: 'finish',    japanese: '終える',     example: 'I finished my homework.', notes: '動詞' },
      { english: 'start',     japanese: '始める',     example: 'Let\'s start the lesson.', notes: '動詞' },
      { english: 'stop',      japanese: '止まる・やめる', example: 'Please stop talking.', notes: '動詞' },
      { english: 'bring',     japanese: '持ってくる', example: 'Bring your textbook.', notes: '動詞' },
      { english: 'show',      japanese: '見せる',     example: 'Show me your passport.', notes: '動詞' },
      { english: 'ask',       japanese: '尋ねる・頼む', example: 'May I ask a question?', notes: '動詞' },
      { english: 'answer',    japanese: '答える',     example: 'Please answer the question.', notes: '動詞' },
      { english: 'call',      japanese: '電話する・呼ぶ', example: 'I will call you later.', notes: '動詞' },
      { english: 'visit',     japanese: '訪れる',     example: 'We visited Kyoto last year.', notes: '動詞' },
      { english: 'wait',      japanese: '待つ',       example: 'Wait here, please.', notes: '動詞' },
      { english: 'change',    japanese: '変える・変わる', example: 'Things change over time.', notes: '動詞' },
      { english: 'need',      japanese: '必要とする', example: 'I need more time.', notes: '動詞' },
      { english: 'love',      japanese: '愛する・大好きだ', example: 'I love Japanese food.', notes: '動詞' },
      { english: 'like',      japanese: '好き',       example: 'Do you like sushi?', notes: '動詞' },
      { english: 'hate',      japanese: '嫌う',       example: 'I hate being late.', notes: '動詞' },
      // 形容詞（追加）
      { english: 'hungry',    japanese: 'お腹が空いた', example: 'I am very hungry.', notes: '形容詞' },
      { english: 'thirsty',   japanese: '喉が渇いた', example: 'Are you thirsty?', notes: '形容詞' },
      { english: 'tired',     japanese: '疲れた',     example: 'I am so tired today.', notes: '形容詞' },
      { english: 'sick',      japanese: '病気の',     example: 'She stayed home because she was sick.', notes: '形容詞' },
      { english: 'healthy',   japanese: '健康な',     example: 'Eat healthy food.', notes: '形容詞' },
      { english: 'safe',      japanese: '安全な',     example: 'Is it safe to go out?', notes: '形容詞' },
      { english: 'clean',     japanese: 'きれいな・清潔な', example: 'Keep your room clean.', notes: '形容詞' },
      { english: 'quiet',     japanese: '静かな',     example: 'Please be quiet.', notes: '形容詞' },
      { english: 'loud',      japanese: 'うるさい・大きな音の', example: 'The music is too loud.', notes: '形容詞' },
      { english: 'fast',      japanese: '速い',       example: 'She is a fast runner.', notes: '形容詞' },
      { english: 'slow',      japanese: '遅い',       example: 'Please walk slowly.', notes: '形容詞' },
      { english: 'funny',     japanese: '面白い・おかしい', example: 'That joke was very funny.', notes: '形容詞' },
      { english: 'cute',      japanese: 'かわいい',   example: 'What a cute baby!', notes: '形容詞' },
      { english: 'strange',   japanese: '変な・不思議な', example: 'That is a strange sound.', notes: '形容詞' },
      { english: 'popular',   japanese: '人気のある', example: 'This singer is very popular.', notes: '形容詞' },
      { english: 'same',      japanese: '同じ',       example: 'We have the same bag.', notes: '形容詞' },
      { english: 'different', japanese: '違う・異なる', example: 'We have different opinions.', notes: '形容詞' },
      { english: 'special',   japanese: '特別な',     example: 'Today is a special day.', notes: '形容詞' },
      { english: 'important', japanese: '重要な',     example: 'Health is important.', notes: '形容詞' },
      // 場所・方向
      { english: 'here',      japanese: 'ここ',       example: 'Come here, please.', notes: '場所・方向' },
      { english: 'there',     japanese: 'そこ・あそこ', example: 'Put it over there.', notes: '場所・方向' },
      { english: 'left',      japanese: '左',         example: 'Turn left at the corner.', notes: '方向' },
      { english: 'right',     japanese: '右',         example: 'Turn right here.', notes: '方向' },
      { english: 'front',     japanese: '前',         example: 'Stand in front of me.', notes: '方向' },
      { english: 'behind',    japanese: '後ろ',       example: 'The store is behind the school.', notes: '方向' },
      { english: 'near',      japanese: '近い・近くに', example: 'Is there a station near here?', notes: '方向' },
      // 乗り物
      { english: 'car',       japanese: '車',         example: 'My father drives a car.', notes: '乗り物' },
      { english: 'bus',       japanese: 'バス',       example: 'I take the bus to school.', notes: '乗り物' },
      { english: 'train',     japanese: '電車',       example: 'The train is crowded.', notes: '乗り物' },
      { english: 'bike',      japanese: '自転車',     example: 'I ride my bike to school.', notes: '乗り物' },
      // スポーツ・趣味
      { english: 'sport',     japanese: 'スポーツ',   example: 'I like sports.', notes: '趣味' },
      { english: 'music',     japanese: '音楽',       example: 'I love listening to music.', notes: '趣味' },
      { english: 'movie',     japanese: '映画',       example: 'I watched a great movie.', notes: '趣味' },
      { english: 'game',      japanese: 'ゲーム',     example: 'Do you like video games?', notes: '趣味' },
      { english: 'trip',      japanese: '旅行',       example: 'We went on a trip to Kyoto.', notes: '旅行' },
      // 体
      { english: 'eye',       japanese: '目',         example: 'She has beautiful eyes.', notes: '体' },
      { english: 'hand',      japanese: '手',         example: 'Wash your hands before eating.', notes: '体' },
      { english: 'head',      japanese: '頭',         example: 'My head hurts.', notes: '体' },
      { english: 'heart',     japanese: '心・心臓',   example: 'My heart beats fast.', notes: '体' },
      { english: 'voice',     japanese: '声',         example: 'She has a beautiful voice.', notes: '体' },
    ]
  },

  high: {
    label: '高校レベル',
    description: '高校英語・大学入試頻出単語（約100語）',
    color: '#2563eb',
    words: [
      // 動詞
      { english: 'achieve',     japanese: '達成する',       example: 'She achieved her goal.', notes: '重要動詞' },
      { english: 'develop',     japanese: '発展させる・開発する', example: 'They developed a new product.', notes: '重要動詞' },
      { english: 'improve',     japanese: '改善する',       example: 'I want to improve my English.', notes: '重要動詞' },
      { english: 'increase',    japanese: '増加する',       example: 'Sales increased by 20%.', notes: '重要動詞' },
      { english: 'decrease',    japanese: '減少する',       example: 'The population decreased.', notes: '重要動詞' },
      { english: 'provide',     japanese: '提供する',       example: 'The company provides free meals.', notes: '重要動詞' },
      { english: 'require',     japanese: '必要とする',     example: 'This job requires experience.', notes: '重要動詞' },
      { english: 'consider',    japanese: '考慮する',       example: 'Please consider my proposal.', notes: '重要動詞' },
      { english: 'suggest',     japanese: '提案する',       example: 'She suggested a new plan.', notes: '重要動詞' },
      { english: 'protect',     japanese: '保護する',       example: 'We must protect the environment.', notes: '重要動詞' },
      { english: 'support',     japanese: '支持する・支援する', example: 'I support your idea.', notes: '重要動詞' },
      { english: 'influence',   japanese: '影響を与える',   example: 'Music influences our emotions.', notes: '重要動詞' },
      { english: 'affect',      japanese: '影響する',       example: 'Weather affects our mood.', notes: '重要動詞' },
      { english: 'produce',     japanese: '生産する・生み出す', example: 'Japan produces many cars.', notes: '重要動詞' },
      { english: 'reduce',      japanese: '減らす',         example: 'We should reduce waste.', notes: '重要動詞' },
      { english: 'express',     japanese: '表現する',       example: 'He expressed his feelings.', notes: '重要動詞' },
      { english: 'explain',     japanese: '説明する',       example: 'Can you explain this problem?', notes: '重要動詞' },
      { english: 'allow',       japanese: '許可する',       example: 'Smoking is not allowed here.', notes: '重要動詞' },
      { english: 'prevent',     japanese: '防ぐ',           example: 'Exercise prevents illness.', notes: '重要動詞' },
      { english: 'compare',     japanese: '比較する',       example: 'Compare these two options.', notes: '重要動詞' },
      // 名詞
      { english: 'society',     japanese: '社会',           example: 'We live in a complex society.', notes: '名詞' },
      { english: 'culture',     japanese: '文化',           example: 'Japanese culture is unique.', notes: '名詞' },
      { english: 'environment', japanese: '環境',           example: 'We must protect the environment.', notes: '名詞' },
      { english: 'experience',  japanese: '経験',           example: 'Travel gives us new experiences.', notes: '名詞' },
      { english: 'opportunity', japanese: '機会・チャンス', example: 'This is a great opportunity.', notes: '名詞' },
      { english: 'education',   japanese: '教育',           example: 'Education is important for everyone.', notes: '名詞' },
      { english: 'knowledge',   japanese: '知識',           example: 'Knowledge is power.', notes: '名詞' },
      { english: 'population',  japanese: '人口',           example: 'Japan\'s population is aging.', notes: '名詞' },
      { english: 'technology',  japanese: '技術・テクノロジー', example: 'Technology changes our lives.', notes: '名詞' },
      { english: 'economy',     japanese: '経済',           example: 'The economy is growing.', notes: '名詞' },
      { english: 'government',  japanese: '政府',           example: 'The government made a new law.', notes: '名詞' },
      { english: 'community',   japanese: 'コミュニティ・地域社会', example: 'We should help our community.', notes: '名詞' },
      { english: 'tradition',   japanese: '伝統',           example: 'We should respect our traditions.', notes: '名詞' },
      { english: 'relationship', japanese: '関係',          example: 'Good relationships are important.', notes: '名詞' },
      { english: 'purpose',     japanese: '目的',           example: 'What is the purpose of this meeting?', notes: '名詞' },
      { english: 'challenge',   japanese: '課題・挑戦',     example: 'Life is full of challenges.', notes: '名詞' },
      { english: 'solution',    japanese: '解決策',         example: 'We need to find a solution.', notes: '名詞' },
      { english: 'reason',      japanese: '理由',           example: 'Tell me the reason.', notes: '名詞' },
      { english: 'result',      japanese: '結果',           example: 'What was the result?', notes: '名詞' },
      { english: 'effort',      japanese: '努力',           example: 'Success requires hard effort.', notes: '名詞' },
      { english: 'ability',     japanese: '能力',           example: 'She has great ability.', notes: '名詞' },
      { english: 'difference',  japanese: '違い',           example: 'What is the difference?', notes: '名詞' },
      { english: 'opinion',     japanese: '意見',           example: 'Please share your opinion.', notes: '名詞' },
      { english: 'advantage',   japanese: '利点・メリット', example: 'What are the advantages?', notes: '名詞' },
      { english: 'disadvantage', japanese: '欠点・デメリット', example: 'Every plan has disadvantages.', notes: '名詞' },
      // 形容詞
      { english: 'important',   japanese: '重要な',         example: 'This is an important decision.', notes: '形容詞' },
      { english: 'necessary',   japanese: '必要な',         example: 'Sleep is necessary for health.', notes: '形容詞' },
      { english: 'possible',    japanese: '可能な',         example: 'Is it possible to finish today?', notes: '形容詞' },
      { english: 'serious',     japanese: '深刻な・真剣な', example: 'This is a serious problem.', notes: '形容詞' },
      { english: 'various',     japanese: '様々な',         example: 'There are various opinions.', notes: '形容詞' },
      { english: 'global',      japanese: 'グローバルな・世界的な', example: 'Climate change is a global problem.', notes: '形容詞' },
      { english: 'local',       japanese: '地元の・地域の', example: 'I shop at the local market.', notes: '形容詞' },
      { english: 'modern',      japanese: '現代の',         example: 'Modern technology is amazing.', notes: '形容詞' },
      { english: 'traditional', japanese: '伝統的な',       example: 'I prefer traditional food.', notes: '形容詞' },
      { english: 'natural',     japanese: '自然の・当然の', example: 'Natural disasters are increasing.', notes: '形容詞' },
      { english: 'creative',    japanese: '創造的な',       example: 'She is a creative designer.', notes: '形容詞' },
      { english: 'effective',   japanese: '効果的な',       example: 'This is an effective method.', notes: '形容詞' },
      { english: 'successful',  japanese: '成功した',       example: 'He became a successful businessman.', notes: '形容詞' },
      { english: 'responsible', japanese: '責任感のある',   example: 'Be responsible for your actions.', notes: '形容詞' },
      { english: 'independent', japanese: '独立した・自立した', example: 'She is very independent.', notes: '形容詞' },
      // 副詞・接続詞
      { english: 'however',     japanese: 'しかしながら',   example: 'I like it; however, it is expensive.', notes: '接続詞' },
      { english: 'therefore',   japanese: 'したがって',     example: 'It rained; therefore the game was canceled.', notes: '接続詞' },
      { english: 'although',    japanese: '〜にもかかわらず', example: 'Although it was cold, he went out.', notes: '接続詞' },
      { english: 'moreover',    japanese: 'さらに',         example: 'Moreover, the price is low.', notes: '接続詞' },
      { english: 'nevertheless', japanese: 'それにもかかわらず', example: 'Nevertheless, she kept going.', notes: '副詞' },
      { english: 'gradually',   japanese: '徐々に',         example: 'The situation gradually improved.', notes: '副詞' },
      { english: 'recently',    japanese: '最近',           example: 'I recently moved here.', notes: '副詞' },
      { english: 'actually',    japanese: '実際に',         example: 'Actually, I was wrong.', notes: '副詞' },
      { english: 'especially',  japanese: '特に',           example: 'I especially like sushi.', notes: '副詞' },
      { english: 'generally',   japanese: '一般的に',       example: 'Generally, people dislike change.', notes: '副詞' },
      // 熟語・イディオム
      { english: 'give up',     japanese: '諦める',         example: 'Never give up your dreams.', notes: '熟語' },
      { english: 'take care',   japanese: '気をつける・世話をする', example: 'Take care of yourself.', notes: '熟語' },
      { english: 'look forward to', japanese: '〜を楽しみにする', example: 'I look forward to seeing you.', notes: '熟語' },
      { english: 'make sense',  japanese: '意味をなす',     example: 'Does this make sense?', notes: '熟語' },
      { english: 'on the other hand', japanese: '一方で',   example: 'On the other hand, there are risks.', notes: '熟語' },
      { english: 'as a result', japanese: 'その結果',       example: 'As a result, we succeeded.', notes: '熟語' },
      { english: 'in order to', japanese: '〜するために',   example: 'I study hard in order to pass.', notes: '熟語' },
      { english: 'in addition', japanese: 'さらに',         example: 'In addition, it is affordable.', notes: '熟語' },
      { english: 'for example', japanese: '例えば',         example: 'For example, apples are healthy.', notes: '熟語' },
      { english: 'such as',     japanese: 'たとえば〜のような', example: 'Fruits such as apples and oranges.', notes: '熟語' },
      // 動詞（追加）
      { english: 'accomplish',  japanese: '成し遂げる',     example: 'She accomplished her dream.', notes: '重要動詞' },
      { english: 'adapt',       japanese: '適応する',       example: 'We must adapt to change.', notes: '重要動詞' },
      { english: 'approach',    japanese: 'アプローチする・近づく', example: 'Let us approach this differently.', notes: '重要動詞' },
      { english: 'assess',      japanese: '評価する・査定する', example: 'Assess the risk carefully.', notes: '重要動詞' },
      { english: 'boost',       japanese: '高める・増やす', example: 'Exercise boosts your energy.', notes: '重要動詞' },
      { english: 'clarify',     japanese: '明確にする',     example: 'Please clarify your point.', notes: '重要動詞' },
      { english: 'convince',    japanese: '説得する',       example: 'She convinced him to try.', notes: '重要動詞' },
      { english: 'cope',        japanese: '対処する',       example: 'How do you cope with stress?', notes: '重要動詞' },
      { english: 'demand',      japanese: '要求する',       example: 'The job demands a lot of effort.', notes: '重要動詞' },
      { english: 'enable',      japanese: '可能にする',     example: 'Technology enables faster work.', notes: '重要動詞' },
      { english: 'enhance',     japanese: '高める・向上させる', example: 'Reading enhances your vocabulary.', notes: '重要動詞' },
      { english: 'expand',      japanese: '拡大する',       example: 'The company plans to expand.', notes: '重要動詞' },
      { english: 'foster',      japanese: '育てる・促進する', example: 'Foster good relationships.', notes: '重要動詞' },
      { english: 'overcome',    japanese: '克服する',       example: 'Overcome your fears.', notes: '重要動詞' },
      { english: 'promote',     japanese: '促進する・昇進させる', example: 'Promote healthy habits.', notes: '重要動詞' },
      { english: 'reflect',     japanese: '反省する・反映する', example: 'Reflect on your actions.', notes: '重要動詞' },
      { english: 'resolve',     japanese: '解決する',       example: 'Resolve the conflict peacefully.', notes: '重要動詞' },
      { english: 'transform',   japanese: '変革する',       example: 'The internet transformed our lives.', notes: '重要動詞' },
      { english: 'seek',        japanese: '求める・探す',   example: 'Always seek to improve.', notes: '重要動詞' },
      { english: 'identify',    japanese: '特定する',       example: 'Identify the main issue.', notes: '重要動詞' },
      // 名詞（追加）
      { english: 'attitude',    japanese: '態度・姿勢',     example: 'Have a positive attitude.', notes: '名詞' },
      { english: 'awareness',   japanese: '意識・認識',     example: 'Raise awareness about the issue.', notes: '名詞' },
      { english: 'behavior',    japanese: '行動・振る舞い', example: 'Good behavior is appreciated.', notes: '名詞' },
      { english: 'benefit',     japanese: '利益・恩恵',     example: 'Exercise has many benefits.', notes: '名詞' },
      { english: 'conflict',    japanese: '対立・紛争',     example: 'Avoid unnecessary conflict.', notes: '名詞' },
      { english: 'debate',      japanese: '議論・討論',     example: 'There is a debate on this issue.', notes: '名詞' },
      { english: 'discovery',   japanese: '発見',           example: 'The discovery changed science.', notes: '名詞' },
      { english: 'expectation', japanese: '期待',           example: 'Meet the expectations.', notes: '名詞' },
      { english: 'leadership',  japanese: 'リーダーシップ', example: 'Good leadership is essential.', notes: '名詞' },
      { english: 'limitation',  japanese: '限界・制限',     example: 'Know your limitations.', notes: '名詞' },
      { english: 'media',       japanese: 'メディア',       example: 'Social media is powerful.', notes: '名詞' },
      { english: 'motivation',  japanese: '動機・モチベーション', example: 'What is your motivation?', notes: '名詞' },
      { english: 'outcome',     japanese: '結果・成果',     example: 'The outcome was positive.', notes: '名詞' },
      { english: 'potential',   japanese: '可能性・潜在力', example: 'You have great potential.', notes: '名詞' },
      { english: 'priority',    japanese: '優先事項',       example: 'Health is my top priority.', notes: '名詞' },
      { english: 'progress',    japanese: '進歩・進展',     example: 'We are making good progress.', notes: '名詞' },
      { english: 'trend',       japanese: 'トレンド・傾向', example: 'Follow the latest trends.', notes: '名詞' },
      { english: 'value',       japanese: '価値・価値観',   example: 'Family values are important.', notes: '名詞' },
      { english: 'vision',      japanese: 'ビジョン・見通し', example: 'The leader has a clear vision.', notes: '名詞' },
      { english: 'norm',        japanese: '規範・標準',     example: 'That is the social norm.', notes: '名詞' },
      // 形容詞（追加）
      { english: 'accurate',    japanese: '正確な',         example: 'Give an accurate answer.', notes: '形容詞' },
      { english: 'appropriate', japanese: '適切な',         example: 'Choose appropriate words.', notes: '形容詞' },
      { english: 'capable',     japanese: '有能な・できる', example: 'She is capable of more.', notes: '形容詞' },
      { english: 'crucial',     japanese: '非常に重要な',   example: 'This is a crucial decision.', notes: '形容詞' },
      { english: 'distinct',    japanese: '明確に異なる',   example: 'They have distinct personalities.', notes: '形容詞' },
      { english: 'efficient',   japanese: '効率的な',       example: 'Find a more efficient way.', notes: '形容詞' },
      { english: 'essential',   japanese: '不可欠な',       example: 'Water is essential for life.', notes: '形容詞' },
      { english: 'flexible',    japanese: '柔軟な',         example: 'Be flexible in your approach.', notes: '形容詞' },
      { english: 'logical',     japanese: '論理的な',       example: 'Give a logical explanation.', notes: '形容詞' },
      { english: 'obvious',     japanese: '明らかな',       example: 'The answer is obvious.', notes: '形容詞' },
      { english: 'precise',     japanese: '正確な・精密な', example: 'Be precise in your writing.', notes: '形容詞' },
      { english: 'realistic',   japanese: '現実的な',       example: 'Set realistic goals.', notes: '形容詞' },
      { english: 'stable',      japanese: '安定した',       example: 'A stable income is important.', notes: '形容詞' },
      { english: 'temporary',   japanese: '一時的な',       example: 'This is a temporary solution.', notes: '形容詞' },
      { english: 'unique',      japanese: '独自の・唯一の', example: 'Everyone is unique.', notes: '形容詞' },
      { english: 'visible',     japanese: '目に見える',     example: 'The effect is clearly visible.', notes: '形容詞' },
    ]
  },

  college: {
    label: '大学レベル',
    description: '大学英語・TOEIC/TOEFL頻出単語（約100語）',
    color: '#7c3aed',
    words: [
      // 学術動詞
      { english: 'analyze',      japanese: '分析する',       example: 'We analyzed the data carefully.', notes: '学術動詞' },
      { english: 'evaluate',     japanese: '評価する',       example: 'Please evaluate the results.', notes: '学術動詞' },
      { english: 'establish',    japanese: '確立する・設立する', example: 'They established a new company.', notes: '学術動詞' },
      { english: 'demonstrate',  japanese: '示す・実証する', example: 'The study demonstrates the effect.', notes: '学術動詞' },
      { english: 'investigate',  japanese: '調査する',       example: 'Scientists investigated the cause.', notes: '学術動詞' },
      { english: 'contribute',   japanese: '貢献する',       example: 'She contributed greatly to the project.', notes: '学術動詞' },
      { english: 'emphasize',    japanese: '強調する',       example: 'He emphasized the importance of health.', notes: '学術動詞' },
      { english: 'implement',    japanese: '実施する・実装する', example: 'We implemented the new policy.', notes: '学術動詞' },
      { english: 'maintain',     japanese: '維持する',       example: 'It is hard to maintain good habits.', notes: '学術動詞' },
      { english: 'acknowledge',  japanese: '認める',         example: 'He acknowledged his mistake.', notes: '学術動詞' },
      { english: 'acquire',      japanese: '習得する・取得する', example: 'She acquired new skills quickly.', notes: '学術動詞' },
      { english: 'assume',       japanese: '仮定する・推測する', example: 'Let us assume the hypothesis is true.', notes: '学術動詞' },
      { english: 'interpret',    japanese: '解釈する',       example: 'How do you interpret this data?', notes: '学術動詞' },
      { english: 'justify',      japanese: '正当化する',     example: 'Can you justify this decision?', notes: '学術動詞' },
      { english: 'modify',       japanese: '修正する',       example: 'We need to modify our approach.', notes: '学術動詞' },
      { english: 'obtain',       japanese: '得る・入手する', example: 'We obtained permission to proceed.', notes: '学術動詞' },
      { english: 'propose',      japanese: '提案する',       example: 'She proposed a new theory.', notes: '学術動詞' },
      { english: 'indicate',     japanese: '示す・指摘する', example: 'The results indicate a clear trend.', notes: '学術動詞' },
      { english: 'generate',     japanese: '生み出す・発生させる', example: 'Solar panels generate electricity.', notes: '学術動詞' },
      { english: 'stimulate',    japanese: '刺激する',       example: 'Exercise stimulates brain activity.', notes: '学術動詞' },
      // 学術名詞
      { english: 'hypothesis',   japanese: '仮説',           example: 'The hypothesis was proven correct.', notes: '学術名詞' },
      { english: 'phenomenon',   japanese: '現象',           example: 'Global warming is a natural phenomenon.', notes: '学術名詞' },
      { english: 'perspective',  japanese: '視点・見方',     example: 'See it from a different perspective.', notes: '学術名詞' },
      { english: 'principle',    japanese: '原則・原理',     example: 'Follow the basic principles.', notes: '学術名詞' },
      { english: 'strategy',     japanese: '戦略',           example: 'We need a better strategy.', notes: '学術名詞' },
      { english: 'framework',    japanese: '枠組み・フレームワーク', example: 'Use a clear framework.', notes: '学術名詞' },
      { english: 'policy',       japanese: '政策・方針',     example: 'The government changed its policy.', notes: '学術名詞' },
      { english: 'factor',       japanese: '要因',           example: 'What factors led to success?', notes: '学術名詞' },
      { english: 'evidence',     japanese: '証拠',           example: 'We need more evidence.', notes: '学術名詞' },
      { english: 'concept',      japanese: '概念',           example: 'This is a difficult concept to grasp.', notes: '学術名詞' },
      { english: 'consequence',  japanese: '結果・影響',     example: 'Consider the consequences.', notes: '学術名詞' },
      { english: 'aspect',       japanese: '側面・観点',     example: 'Consider every aspect of the problem.', notes: '学術名詞' },
      { english: 'context',      japanese: '文脈・状況',     example: 'Understand the historical context.', notes: '学術名詞' },
      { english: 'impact',       japanese: '影響・衝撃',     example: 'The internet has a huge impact on society.', notes: '学術名詞' },
      { english: 'innovation',   japanese: '革新',           example: 'Innovation drives economic growth.', notes: '学術名詞' },
      { english: 'diversity',    japanese: '多様性',         example: 'Diversity makes teams stronger.', notes: '学術名詞' },
      { english: 'sustainability', japanese: '持続可能性',   example: 'Sustainability is key to the future.', notes: '学術名詞' },
      { english: 'infrastructure', japanese: 'インフラ',     example: 'The city needs better infrastructure.', notes: '学術名詞' },
      { english: 'hierarchy',    japanese: '階層',           example: 'There is a strict hierarchy here.', notes: '学術名詞' },
      { english: 'collaboration', japanese: '協力・協働',    example: 'Collaboration leads to better results.', notes: '学術名詞' },
      { english: 'controversy',  japanese: '論争・議論',     example: 'There is controversy over this issue.', notes: '学術名詞' },
      { english: 'incentive',    japanese: '動機・インセンティブ', example: 'Financial incentives motivate workers.', notes: '学術名詞' },
      { english: 'perception',   japanese: '認識・知覚',     example: 'Our perception shapes our reality.', notes: '学術名詞' },
      { english: 'parameter',    japanese: 'パラメーター・要素', example: 'Define the parameters first.', notes: '学術名詞' },
      // 形容詞
      { english: 'significant',  japanese: '重要な・顕著な', example: 'There is a significant difference.', notes: '形容詞' },
      { english: 'fundamental',  japanese: '根本的な・基本的な', example: 'This is a fundamental problem.', notes: '形容詞' },
      { english: 'comprehensive', japanese: '包括的な',      example: 'We need a comprehensive plan.', notes: '形容詞' },
      { english: 'substantial',  japanese: '実質的な・かなりの', example: 'There was a substantial improvement.', notes: '形容詞' },
      { english: 'sophisticated', japanese: '洗練された・高度な', example: 'This is a sophisticated system.', notes: '形容詞' },
      { english: 'controversial', japanese: '論争的な',      example: 'This is a controversial topic.', notes: '形容詞' },
      { english: 'inevitable',   japanese: '避けられない',   example: 'Change is inevitable.', notes: '形容詞' },
      { english: 'consistent',   japanese: '一貫した',       example: 'Be consistent in your efforts.', notes: '形容詞' },
      { english: 'relevant',     japanese: '関連した',       example: 'Please provide relevant information.', notes: '形容詞' },
      { english: 'ambiguous',    japanese: '曖昧な',         example: 'His answer was ambiguous.', notes: '形容詞' },
      { english: 'explicit',     japanese: '明確な・明示的な', example: 'Please be more explicit.', notes: '形容詞' },
      { english: 'implicit',     japanese: '暗黙の・暗示的な', example: 'There was an implicit agreement.', notes: '形容詞' },
      { english: 'empirical',    japanese: '経験的な・実証的な', example: 'We need empirical evidence.', notes: '形容詞' },
      { english: 'cognitive',    japanese: '認知の',         example: 'This affects cognitive ability.', notes: '形容詞' },
      { english: 'ethical',      japanese: '倫理的な',       example: 'Consider the ethical implications.', notes: '形容詞' },
      // ビジネス・社会
      { english: 'allocate',     japanese: '割り当てる・配分する', example: 'Allocate resources efficiently.', notes: 'ビジネス' },
      { english: 'optimize',     japanese: '最適化する',     example: 'We need to optimize the process.', notes: 'ビジネス' },
      { english: 'prioritize',   japanese: '優先する',       example: 'Prioritize your most important tasks.', notes: 'ビジネス' },
      { english: 'delegate',     japanese: '委任する',       example: 'Learn to delegate tasks.', notes: 'ビジネス' },
      { english: 'negotiate',    japanese: '交渉する',       example: 'They negotiated a better deal.', notes: 'ビジネス' },
      { english: 'facilitate',   japanese: '促進する・容易にする', example: 'Technology facilitates communication.', notes: 'ビジネス' },
      { english: 'coordinate',   japanese: '調整する',       example: 'She coordinates the team well.', notes: 'ビジネス' },
      { english: 'benchmark',    japanese: '基準・ベンチマーク', example: 'Set a benchmark for success.', notes: 'ビジネス' },
      { english: 'milestone',    japanese: '節目・重要な目標', example: 'We reached an important milestone.', notes: 'ビジネス' },
      { english: 'momentum',     japanese: '勢い・モメンタム', example: 'Keep the momentum going.', notes: 'ビジネス' },
      // 学術副詞・接続詞
      { english: 'furthermore',  japanese: 'さらに・加えて',  example: 'Furthermore, the data supports this.', notes: '副詞' },
      { english: 'consequently', japanese: 'その結果として', example: 'Consequently, the project failed.', notes: '副詞' },
      { english: 'nonetheless',  japanese: 'それにもかかわらず', example: 'Nonetheless, we must try.', notes: '副詞' },
      { english: 'alternatively', japanese: 'あるいは・別の方法として', example: 'Alternatively, we could try this.', notes: '副詞' },
      { english: 'predominantly', japanese: '主に・大部分において', example: 'The population is predominantly young.', notes: '副詞' },
      { english: 'simultaneously', japanese: '同時に',        example: 'You can do two things simultaneously.', notes: '副詞' },
      { english: 'presumably',   japanese: 'おそらく',        example: 'Presumably, they know the answer.', notes: '副詞' },
      { english: 'inherently',   japanese: '本質的に',        example: 'The system is inherently flawed.', notes: '副詞' },
      // 学術動詞（追加）
      { english: 'advocate',     japanese: '提唱する・支持する', example: 'She advocates for equal rights.', notes: '学術動詞' },
      { english: 'articulate',   japanese: '明確に表現する',  example: 'Articulate your ideas clearly.', notes: '学術動詞' },
      { english: 'assess',       japanese: '評価する',        example: 'Assess the risks before deciding.', notes: '学術動詞' },
      { english: 'categorize',   japanese: '分類する',        example: 'Categorize the data by type.', notes: '学術動詞' },
      { english: 'conceptualize', japanese: '概念化する',     example: 'Conceptualize the problem first.', notes: '学術動詞' },
      { english: 'consolidate',  japanese: '強化する・統合する', example: 'Consolidate your knowledge.', notes: '学術動詞' },
      { english: 'contextualize', japanese: '文脈化する',     example: 'Contextualize the data.', notes: '学術動詞' },
      { english: 'differentiate', japanese: '区別する',       example: 'Differentiate between the two.', notes: '学術動詞' },
      { english: 'diminish',     japanese: '減少させる',      example: 'Stress can diminish performance.', notes: '学術動詞' },
      { english: 'disclose',     japanese: '開示する',        example: 'Disclose all relevant information.', notes: '学術動詞' },
      { english: 'distinguish',  japanese: '区別する',        example: 'Can you distinguish the difference?', notes: '学術動詞' },
      { english: 'formulate',    japanese: '策定する・作成する', example: 'Formulate a clear plan.', notes: '学術動詞' },
      { english: 'initiate',     japanese: '開始する',        example: 'Initiate a new program.', notes: '学術動詞' },
      { english: 'integrate',    japanese: '統合する',        example: 'Integrate new technology.', notes: '学術動詞' },
      { english: 'mitigate',     japanese: '軽減する',        example: 'Mitigate the risk of failure.', notes: '学術動詞' },
      { english: 'monitor',      japanese: '監視する',        example: 'Monitor the patient\'s condition.', notes: '学術動詞' },
      { english: 'utilize',      japanese: '活用する',        example: 'Utilize available resources.', notes: '学術動詞' },
      { english: 'validate',     japanese: '検証する・証明する', example: 'Validate the results.', notes: '学術動詞' },
      { english: 'verify',       japanese: '確認する・証明する', example: 'Verify the information.', notes: '学術動詞' },
      { english: 'reinforce',    japanese: '強化する',        example: 'Reinforce positive behavior.', notes: '学術動詞' },
      // 学術名詞（追加）
      { english: 'abstraction',  japanese: '抽象・抽象化',   example: 'Abstraction is key in programming.', notes: '学術名詞' },
      { english: 'ambiguity',    japanese: '曖昧さ',          example: 'Avoid ambiguity in writing.', notes: '学術名詞' },
      { english: 'autonomy',     japanese: '自律性・自治',   example: 'Respect the autonomy of individuals.', notes: '学術名詞' },
      { english: 'bias',         japanese: '偏り・バイアス', example: 'Avoid confirmation bias.', notes: '学術名詞' },
      { english: 'causality',    japanese: '因果関係',        example: 'Prove causality, not correlation.', notes: '学術名詞' },
      { english: 'coherence',    japanese: '一貫性',          example: 'The argument lacks coherence.', notes: '学術名詞' },
      { english: 'competence',   japanese: '能力・適格性',   example: 'Demonstrate your competence.', notes: '学術名詞' },
      { english: 'consensus',    japanese: '合意・コンセンサス', example: 'Reach a consensus.', notes: '学術名詞' },
      { english: 'correlation',  japanese: '相関関係',        example: 'There is a strong correlation.', notes: '学術名詞' },
      { english: 'deficit',      japanese: '不足・赤字',      example: 'Address the budget deficit.', notes: '学術名詞' },
      { english: 'discourse',    japanese: '言説・議論',      example: 'Academic discourse is important.', notes: '学術名詞' },
      { english: 'dynamic',      japanese: 'ダイナミクス・力学', example: 'Understand the team dynamics.', notes: '学術名詞' },
      { english: 'equilibrium',  japanese: '均衡・平衡',      example: 'Maintain equilibrium in the system.', notes: '学術名詞' },
      { english: 'globalization', japanese: 'グローバル化',   example: 'Globalization has pros and cons.', notes: '学術名詞' },
      { english: 'ideology',     japanese: 'イデオロギー',    example: 'Political ideology shapes policy.', notes: '学術名詞' },
      { english: 'implication',  japanese: '示唆・含意',      example: 'Consider the implications.', notes: '学術名詞' },
      { english: 'institution',  japanese: '機関・制度',      example: 'Educational institutions are vital.', notes: '学術名詞' },
      { english: 'mechanism',    japanese: 'メカニズム・仕組み', example: 'Explain the mechanism.', notes: '学術名詞' },
      { english: 'paradigm',     japanese: 'パラダイム・枠組み', example: 'A paradigm shift is needed.', notes: '学術名詞' },
      { english: 'productivity', japanese: '生産性',          example: 'Improve team productivity.', notes: '学術名詞' },
      { english: 'rationale',    japanese: '根拠・理由',      example: 'Explain the rationale.', notes: '学術名詞' },
      { english: 'resilience',   japanese: '回復力・レジリエンス', example: 'Build resilience in difficult times.', notes: '学術名詞' },
      { english: 'rhetoric',     japanese: '修辞法・言説',    example: 'Powerful rhetoric influences people.', notes: '学術名詞' },
      { english: 'transparency', japanese: '透明性',          example: 'Demand transparency in government.', notes: '学術名詞' },
      { english: 'variable',     japanese: '変数・変動要因',  example: 'Control for all variables.', notes: '学術名詞' },
      // 形容詞（追加）
      { english: 'abstract',     japanese: '抽象的な',        example: 'This is an abstract concept.', notes: '形容詞' },
      { english: 'adequate',     japanese: '適切な・十分な',  example: 'Is the budget adequate?', notes: '形容詞' },
      { english: 'analogous',    japanese: '類似した',        example: 'This is analogous to that case.', notes: '形容詞' },
      { english: 'arbitrary',    japanese: '恣意的な',        example: 'The decision seemed arbitrary.', notes: '形容詞' },
      { english: 'cumulative',   japanese: '累積的な',        example: 'The cumulative effect is large.', notes: '形容詞' },
      { english: 'detrimental',  japanese: '有害な',          example: 'Stress is detrimental to health.', notes: '形容詞' },
      { english: 'hierarchical', japanese: '階層的な',        example: 'A hierarchical structure.', notes: '形容詞' },
      { english: 'innovative',   japanese: '革新的な',        example: 'An innovative approach.', notes: '形容詞' },
      { english: 'mutual',       japanese: '相互の',          example: 'Mutual respect is important.', notes: '形容詞' },
      { english: 'negligible',   japanese: '無視できる',      example: 'The difference is negligible.', notes: '形容詞' },
      { english: 'objective',    japanese: '客観的な・目標', example: 'Be objective in your analysis.', notes: '形容詞' },
      { english: 'obsolete',     japanese: '時代遅れの',      example: 'This technology is obsolete.', notes: '形容詞' },
      { english: 'prevalent',    japanese: '普及している',    example: 'This is a prevalent view.', notes: '形容詞' },
      { english: 'redundant',    japanese: '余分な・冗長な',  example: 'Avoid redundant information.', notes: '形容詞' },
      { english: 'subjective',   japanese: '主観的な',        example: 'Taste is subjective.', notes: '形容詞' },
      { english: 'systematic',   japanese: '体系的な',        example: 'Use a systematic approach.', notes: '形容詞' },
      { english: 'theoretical',  japanese: '理論的な',        example: 'This is a theoretical model.', notes: '形容詞' },
      // 社会科学・経済
      { english: 'aggregate',    japanese: '集合・集計',      example: 'The aggregate result is positive.', notes: '経済・社会' },
      { english: 'capitalism',   japanese: '資本主義',        example: 'Capitalism drives innovation.', notes: '経済・社会' },
      { english: 'commodity',    japanese: '商品・コモディティ', example: 'Oil is a global commodity.', notes: '経済・社会' },
      { english: 'deregulation', japanese: '規制緩和',        example: 'Deregulation promotes competition.', notes: '経済・社会' },
      { english: 'fiscal',       japanese: '財政の',          example: 'Fiscal policy affects growth.', notes: '経済・社会' },
      { english: 'monetary',     japanese: '金融の',          example: 'Monetary policy controls inflation.', notes: '経済・社会' },
      { english: 'recession',    japanese: '景気後退',        example: 'The recession affected jobs.', notes: '経済・社会' },
      { english: 'speculation',  japanese: '投機・憶測',      example: 'Speculation caused the bubble.', notes: '経済・社会' },
      { english: 'tariff',       japanese: '関税',            example: 'Import tariffs increased.', notes: '経済・社会' },
      { english: 'demographic',  japanese: '人口統計の',      example: 'Study the demographic trends.', notes: '経済・社会' },
    ]
  }
};
