/* ===================================================
   韓国語学習アプリ  words-data.js
   =================================================== */

const WORD_SETS = {
  beginner: {
    label: '初級レベル',
    description: '日常会話の基本単語（約100語）',
    color: '#1d4ed8',
    words: [
      // 挨拶
      { word: '안녕하세요', reading: 'annyeonghaseyo', japanese: 'こんにちは', example: '안녕하세요! 처음 뵙겠습니다.', notes: '挨拶' },
      { word: '감사합니다', reading: 'gamsahamnida', japanese: 'ありがとうございます', example: '도와주셔서 감사합니다.', notes: '挨拶' },
      { word: '죄송합니다', reading: 'joesonghabnida', japanese: 'すみません', example: '늦어서 죄송합니다.', notes: '挨拶' },
      { word: '괜찮아요', reading: 'gwaenchanayo', japanese: '大丈夫です', example: '저는 괜찮아요.', notes: '挨拶' },
      { word: '안녕히 가세요', reading: 'annyeonghi gaseyo', japanese: 'さようなら（見送る側）', example: '안녕히 가세요! 또 오세요.', notes: '挨拶' },
      { word: '안녕히 계세요', reading: 'annyeonghi gyeseyo', japanese: 'さようなら（残る側）', example: '안녕히 계세요. 내일 봬요.', notes: '挨拶' },
      { word: '네', reading: 'ne', japanese: 'はい', example: '네, 알겠습니다.', notes: '挨拶' },
      { word: '아니요', reading: 'aniyo', japanese: 'いいえ', example: '아니요, 괜찮아요.', notes: '挨拶' },
      { word: '반갑습니다', reading: 'bangapseumnida', japanese: 'はじめまして', example: '만나서 반갑습니다.', notes: '挨拶' },
      { word: '잘 부탁드립니다', reading: 'jal butakdeurimnida', japanese: 'よろしくお願いします', example: '앞으로 잘 부탁드립니다.', notes: '挨拶' },
      // 代名詞
      { word: '나', reading: 'na', japanese: '私（くだけた）', example: '나는 학생이에요.', notes: '代名詞' },
      { word: '저', reading: 'jeo', japanese: '私（丁寧）', example: '저는 일본 사람이에요.', notes: '代名詞' },
      { word: '너', reading: 'neo', japanese: 'あなた（くだけた）', example: '너는 어디 살아?', notes: '代名詞' },
      { word: '당신', reading: 'dangsin', japanese: 'あなた（丁寧）', example: '당신은 누구세요?', notes: '代名詞' },
      { word: '그', reading: 'geu', japanese: '彼・その', example: '그는 친구예요.', notes: '代名詞' },
      { word: '그녀', reading: 'geunyeo', japanese: '彼女', example: '그녀는 선생님이에요.', notes: '代名詞' },
      { word: '우리', reading: 'uri', japanese: '私たち', example: '우리는 함께 공부해요.', notes: '代名詞' },
      { word: '이것', reading: 'igeot', japanese: 'これ', example: '이것은 무엇이에요?', notes: '代名詞' },
      { word: '그것', reading: 'geugeot', japanese: 'それ', example: '그것을 주세요.', notes: '代名詞' },
      { word: '저것', reading: 'jeogeot', japanese: 'あれ', example: '저것은 뭐예요?', notes: '代名詞' },
      // 基本動詞
      { word: '이다', reading: 'ida', japanese: '〜である', example: '저는 학생이다.', notes: '動詞' },
      { word: '있다', reading: 'itda', japanese: 'ある・いる', example: '책이 있다.', notes: '動詞' },
      { word: '없다', reading: 'eopda', japanese: 'ない・いない', example: '시간이 없다.', notes: '動詞' },
      { word: '가다', reading: 'gada', japanese: '行く', example: '학교에 가다.', notes: '動詞' },
      { word: '오다', reading: 'oda', japanese: '来る', example: '집에 오다.', notes: '動詞' },
      { word: '먹다', reading: 'meokda', japanese: '食べる', example: '밥을 먹다.', notes: '動詞' },
      { word: '마시다', reading: 'masida', japanese: '飲む', example: '물을 마시다.', notes: '動詞' },
      { word: '자다', reading: 'jada', japanese: '寝る', example: '일찍 자다.', notes: '動詞' },
      { word: '일하다', reading: 'ilhada', japanese: '働く', example: '열심히 일하다.', notes: '動詞' },
      { word: '공부하다', reading: 'gongbuhada', japanese: '勉強する', example: '한국어를 공부하다.', notes: '動詞' },
      { word: '말하다', reading: 'malhada', japanese: '話す', example: '친구에게 말하다.', notes: '動詞' },
      { word: '듣다', reading: 'deutda', japanese: '聴く', example: '음악을 듣다.', notes: '動詞' },
      { word: '보다', reading: 'boda', japanese: '見る', example: '영화를 보다.', notes: '動詞' },
      { word: '쓰다', reading: 'sseuda', japanese: '書く・使う', example: '편지를 쓰다.', notes: '動詞' },
      { word: '읽다', reading: 'ikda', japanese: '読む', example: '책을 읽다.', notes: '動詞' },
      { word: '사다', reading: 'sada', japanese: '買う', example: '물건을 사다.', notes: '動詞' },
      { word: '좋아하다', reading: 'joahada', japanese: '好きである', example: '한국 음식을 좋아하다.', notes: '動詞' },
      { word: '알다', reading: 'alda', japanese: '知っている', example: '이름을 알다.', notes: '動詞' },
      { word: '생각하다', reading: 'saenggakhada', japanese: '思う・考える', example: '열심히 생각하다.', notes: '動詞' },
      { word: '원하다', reading: 'wonhada', japanese: '欲しい・望む', example: '커피를 원하다.', notes: '動詞' },
      // 家族
      { word: '가족', reading: 'gajok', japanese: '家族', example: '우리 가족은 4명이에요.', notes: '家族' },
      { word: '아버지', reading: 'abeoji', japanese: 'お父さん', example: '아버지는 회사원이에요.', notes: '家族' },
      { word: '어머니', reading: 'eomeoni', japanese: 'お母さん', example: '어머니는 선생님이에요.', notes: '家族' },
      { word: '오빠', reading: 'oppa', japanese: 'お兄さん（女性から）', example: '오빠가 밥을 만들었어요.', notes: '家族' },
      { word: '형', reading: 'hyeong', japanese: 'お兄さん（男性から）', example: '형은 대학생이에요.', notes: '家族' },
      { word: '언니', reading: 'eonni', japanese: 'お姉さん（女性から）', example: '언니와 쇼핑했어요.', notes: '家族' },
      { word: '누나', reading: 'nuna', japanese: 'お姉さん（男性から）', example: '누나는 요리를 잘해요.', notes: '家族' },
      { word: '남동생', reading: 'namdongsaeng', japanese: '弟', example: '남동생은 중학생이에요.', notes: '家族' },
      { word: '여동생', reading: 'yeodongsaeng', japanese: '妹', example: '여동생이 귀여워요.', notes: '家族' },
      { word: '친구', reading: 'chingu', japanese: '友達', example: '친구와 같이 놀았어요.', notes: '家族' },
      // 場所
      { word: '학교', reading: 'hakgyo', japanese: '学校', example: '학교에 가요.', notes: '場所' },
      { word: '집', reading: 'jip', japanese: '家', example: '집에서 쉬어요.', notes: '場所' },
      { word: '회사', reading: 'hoesa', japanese: '会社', example: '회사에 출근해요.', notes: '場所' },
      { word: '병원', reading: 'byeongwon', japanese: '病院', example: '병원에 가야 해요.', notes: '場所' },
      { word: '은행', reading: 'eunhaeng', japanese: '銀行', example: '은행에서 돈을 찾았어요.', notes: '場所' },
      { word: '슈퍼마켓', reading: 'syupeomaket', japanese: 'スーパー', example: '슈퍼마켓에서 야채를 샀어요.', notes: '場所' },
      { word: '식당', reading: 'sikdang', japanese: '食堂・レストラン', example: '식당에서 점심을 먹었어요.', notes: '場所' },
      { word: '도서관', reading: 'doseogwan', japanese: '図書館', example: '도서관에서 공부해요.', notes: '場所' },
      { word: '공원', reading: 'gongwon', japanese: '公園', example: '공원에서 산책해요.', notes: '場所' },
      { word: '역', reading: 'yeok', japanese: '駅', example: '역에서 만나요.', notes: '場所' },
      // 食べ物
      { word: '밥', reading: 'bap', japanese: 'ご飯・食事', example: '밥을 먹었어요.', notes: '食べ物' },
      { word: '면', reading: 'myeon', japanese: '麺', example: '면 요리를 좋아해요.', notes: '食べ物' },
      { word: '김치', reading: 'kimchi', japanese: 'キムチ', example: '김치가 매워요.', notes: '食べ物' },
      { word: '불고기', reading: 'bulgogi', japanese: 'プルゴギ', example: '불고기는 정말 맛있어요.', notes: '食べ物' },
      { word: '삼겹살', reading: 'samgyeopsal', japanese: 'サムギョプサル', example: '삼겹살을 구워서 먹어요.', notes: '食べ物' },
      { word: '빵', reading: 'ppang', japanese: 'パン', example: '아침에 빵을 먹어요.', notes: '食べ物' },
      { word: '과일', reading: 'gwail', japanese: '果物', example: '과일을 많이 먹어요.', notes: '食べ物' },
      { word: '야채', reading: 'yachae', japanese: '野菜', example: '야채는 건강에 좋아요.', notes: '食べ物' },
      { word: '고기', reading: 'gogi', japanese: '肉', example: '고기를 좋아해요.', notes: '食べ物' },
      { word: '생선', reading: 'saengseon', japanese: '魚', example: '생선이 신선해요.', notes: '食べ物' },
      { word: '물', reading: 'mul', japanese: '水', example: '물을 마시고 싶어요.', notes: '食べ物' },
      { word: '차', reading: 'cha', japanese: 'お茶', example: '따뜻한 차를 마셔요.', notes: '食べ物' },
      { word: '커피', reading: 'keopi', japanese: 'コーヒー', example: '아침에 커피를 마셔요.', notes: '食べ物' },
      // 数字
      { word: '일', reading: 'il', japanese: '1（漢数字）', example: '일 층에 살아요.', notes: '数字' },
      { word: '이', reading: 'i', japanese: '2（漢数字）', example: '이 명이 왔어요.', notes: '数字' },
      { word: '삼', reading: 'sam', japanese: '3（漢数字）', example: '삼 일이 지났어요.', notes: '数字' },
      { word: '사', reading: 'sa', japanese: '4（漢数字）', example: '사 월이에요.', notes: '数字' },
      { word: '오', reading: 'o', japanese: '5（漢数字）', example: '오 분 기다려요.', notes: '数字' },
      { word: '육', reading: 'yuk', japanese: '6（漢数字）', example: '육 시에 만나요.', notes: '数字' },
      { word: '칠', reading: 'chil', japanese: '7（漢数字）', example: '칠 월은 여름이에요.', notes: '数字' },
      { word: '팔', reading: 'pal', japanese: '8（漢数字）', example: '팔 월에 여행해요.', notes: '数字' },
      { word: '구', reading: 'gu', japanese: '9（漢数字）', example: '구 월에 학교가 시작해요.', notes: '数字' },
      { word: '십', reading: 'sip', japanese: '10（漢数字）', example: '십 분 후에 와요.', notes: '数字' },
      { word: '백', reading: 'baek', japanese: '百', example: '백 원이에요.', notes: '数字' },
      { word: '천', reading: 'cheon', japanese: '千', example: '천 원짜리예요.', notes: '数字' },
      { word: '만', reading: 'man', japanese: '万', example: '만 원을 냈어요.', notes: '数字' },
      // 形容詞
      { word: '크다', reading: 'keuda', japanese: '大きい', example: '이 가방이 너무 커요.', notes: '形容詞' },
      { word: '작다', reading: 'jakda', japanese: '小さい', example: '이 신발은 작아요.', notes: '形容詞' },
      { word: '많다', reading: 'manta', japanese: '多い', example: '사람이 많아요.', notes: '形容詞' },
      { word: '적다', reading: 'jeokda', japanese: '少ない', example: '시간이 적어요.', notes: '形容詞' },
      { word: '좋다', reading: 'jota', japanese: '良い', example: '날씨가 좋아요.', notes: '形容詞' },
      { word: '나쁘다', reading: 'nappeuda', japanese: '悪い', example: '오늘 기분이 나빠요.', notes: '形容詞' },
      { word: '비싸다', reading: 'bissada', japanese: '高い（値段）', example: '이 옷이 너무 비싸요.', notes: '形容詞' },
      { word: '싸다', reading: 'ssada', japanese: '安い', example: '이 가게는 싸요.', notes: '形容詞' },
      { word: '빠르다', reading: 'ppareuda', japanese: '速い', example: '그 차는 빨라요.', notes: '形容詞' },
      { word: '느리다', reading: 'neurida', japanese: '遅い', example: '걸음이 느려요.', notes: '形容詞' },
      { word: '기쁘다', reading: 'gippeuda', japanese: '嬉しい', example: '만나서 기뻐요.', notes: '形容詞' },
      { word: '슬프다', reading: 'seulpeuda', japanese: '悲しい', example: '그 영화는 슬펐어요.', notes: '形容詞' },
      { word: '피곤하다', reading: 'pigonhada', japanese: '疲れた', example: '오늘 많이 피곤해요.', notes: '形容詞' },
      { word: '바쁘다', reading: 'bappeuda', japanese: '忙しい', example: '요즘 많이 바빠요.', notes: '形容詞' },
      { word: '덥다', reading: 'deobda', japanese: '暑い', example: '여름은 너무 더워요.', notes: '形容詞' },
      { word: '춥다', reading: 'chubda', japanese: '寒い', example: '겨울은 추워요.', notes: '形容詞' },
      { word: '예쁘다', reading: 'yeppeuda', japanese: 'きれいだ・かわいい', example: '꽃이 예뻐요.', notes: '形容詞' },
      { word: '맛있다', reading: 'masitda', japanese: 'おいしい', example: '김치찌개가 맛있어요.', notes: '形容詞' },
    ],
  },

  intermediate: {
    label: '中級レベル',
    description: '中級会話の単語（約100語）',
    color: '#1e40af',
    words: [
      // 職業
      { word: '선생님', reading: 'seonsaengnim', japanese: '先生', example: '선생님께 질문했어요.', notes: '職業' },
      { word: '의사', reading: 'uisa', japanese: '医者', example: '의사가 처방전을 써줬어요.', notes: '職業' },
      { word: '엔지니어', reading: 'enjinieo', japanese: 'エンジニア', example: '그는 소프트웨어 엔지니어예요.', notes: '職業' },
      { word: '변호사', reading: 'byeonhosa', japanese: '弁護士', example: '변호사와 상담했어요.', notes: '職業' },
      { word: '간호사', reading: 'ganhosa', japanese: '看護師', example: '간호사가 친절하게 도와줬어요.', notes: '職業' },
      { word: '운전사', reading: 'unjeonsa', japanese: '運転手', example: '버스 운전사가 안전하게 운전해요.', notes: '職業' },
      { word: '요리사', reading: 'yorisa', japanese: '料理人・シェフ', example: '요리사가 맛있는 음식을 만들어요.', notes: '職業' },
      { word: '기자', reading: 'gija', japanese: '記者', example: '기자가 뉴스를 전했어요.', notes: '職業' },
      { word: '경찰', reading: 'gyeongchal', japanese: '警察', example: '경찰이 도와줬어요.', notes: '職業' },
      { word: '사업가', reading: 'saeobga', japanese: 'ビジネスマン・実業家', example: '그는 성공한 사업가예요.', notes: '職業' },
      // 時間
      { word: '오늘', reading: 'oneul', japanese: '今日', example: '오늘 날씨가 맑아요.', notes: '時間' },
      { word: '내일', reading: 'naeil', japanese: '明日', example: '내일 만나요.', notes: '時間' },
      { word: '어제', reading: 'eoje', japanese: '昨日', example: '어제 영화를 봤어요.', notes: '時間' },
      { word: '지금', reading: 'jigeum', japanese: '今', example: '지금 어디에 있어요?', notes: '時間' },
      { word: '아까', reading: 'akka', japanese: 'さっき', example: '아까 전화했어요.', notes: '時間' },
      { word: '나중에', reading: 'najunge', japanese: '後で', example: '나중에 연락할게요.', notes: '時間' },
      { word: '아침', reading: 'achim', japanese: '朝・朝食', example: '아침에 운동해요.', notes: '時間' },
      { word: '오후', reading: 'ohu', japanese: '午後', example: '오후에 회의가 있어요.', notes: '時間' },
      { word: '저녁', reading: 'jeonyeok', japanese: '夕方・夕食', example: '저녁을 같이 먹어요.', notes: '時間' },
      { word: '주말', reading: 'jumal', japanese: '週末', example: '주말에 여행 가요.', notes: '時間' },
      { word: '봄', reading: 'bom', japanese: '春', example: '봄에 꽃이 피어요.', notes: '季節' },
      { word: '여름', reading: 'yeoreum', japanese: '夏', example: '여름에 바다에 가요.', notes: '季節' },
      { word: '가을', reading: 'gaeul', japanese: '秋', example: '가을은 단풍이 예뻐요.', notes: '季節' },
      { word: '겨울', reading: 'gyeoul', japanese: '冬', example: '겨울에 눈이 와요.', notes: '季節' },
      // 交通
      { word: '자동차', reading: 'jadongcha', japanese: '車', example: '자동차로 출근해요.', notes: '交通' },
      { word: '기차', reading: 'gicha', japanese: '電車・汽車', example: '기차를 타고 여행해요.', notes: '交通' },
      { word: '버스', reading: 'beoseu', japanese: 'バス', example: '버스로 학교에 가요.', notes: '交通' },
      { word: '지하철', reading: 'jihacheol', japanese: '地下鉄', example: '지하철이 편리해요.', notes: '交通' },
      { word: '비행기', reading: 'bihaenggi', japanese: '飛行機', example: '비행기로 제주도에 갔어요.', notes: '交通' },
      { word: '택시', reading: 'taeksi', japanese: 'タクシー', example: '택시를 불렀어요.', notes: '交通' },
      { word: '자전거', reading: 'jajeongeо', japanese: '自転車', example: '자전거로 공원을 돌아요.', notes: '交通' },
      // 感情
      { word: '행복하다', reading: 'haengbokhada', japanese: '幸せだ', example: '지금 행복해요.', notes: '感情' },
      { word: '화나다', reading: 'hwanada', japanese: '怒る', example: '그 말에 화가 났어요.', notes: '感情' },
      { word: '걱정하다', reading: 'geokjeonghada', japanese: '心配する', example: '건강이 걱정돼요.', notes: '感情' },
      { word: '흥분하다', reading: 'heungbunhada', japanese: '興奮する', example: '경기를 보고 흥분했어요.', notes: '感情' },
      { word: '부끄럽다', reading: 'bukkeureupda', japanese: '恥ずかしい', example: '발표가 부끄러워요.', notes: '感情' },
      { word: '긴장하다', reading: 'ginjanghadа', japanese: '緊張する', example: '면접에서 긴장했어요.', notes: '感情' },
      { word: '편안하다', reading: 'pyeonan hada', japanese: 'リラックスする', example: '집에서 편안해요.', notes: '感情' },
      { word: '외롭다', reading: 'oeropda', japanese: '寂しい', example: '혼자 있으면 외로워요.', notes: '感情' },
      { word: '무섭다', reading: 'museopda', japanese: '怖い', example: '어두운 밤이 무서워요.', notes: '感情' },
      { word: '놀라다', reading: 'nollada', japanese: '驚く', example: '갑자기 놀랐어요.', notes: '感情' },
      // 中級動詞
      { word: '돕다', reading: 'dopda', japanese: '手伝う・助ける', example: '친구를 도와줘요.', notes: '動詞' },
      { word: '시작하다', reading: 'sijakhada', japanese: '始める', example: '새 프로젝트를 시작해요.', notes: '動詞' },
      { word: '끝내다', reading: 'kkeutnаeda', japanese: '終える', example: '숙제를 끝냈어요.', notes: '動詞' },
      { word: '준비하다', reading: 'junbihada', japanese: '準備する', example: '여행을 준비해요.', notes: '動詞' },
      { word: '결정하다', reading: 'gyeoljeonghada', japanese: '決める', example: '진로를 결정했어요.', notes: '動詞' },
      { word: '믿다', reading: 'mitda', japanese: '信じる', example: '그를 믿어요.', notes: '動詞' },
      { word: '이해하다', reading: 'ihaehada', japanese: '理解する', example: '설명을 이해했어요.', notes: '動詞' },
      { word: '해결하다', reading: 'haegyeolhada', japanese: '解決する', example: '문제를 해결했어요.', notes: '動詞' },
      { word: '발견하다', reading: 'balgyeonhada', japanese: '発見する', example: '새로운 방법을 발견했어요.', notes: '動詞' },
      { word: '변하다', reading: 'byeonhada', japanese: '変わる', example: '많이 변했어요.', notes: '動詞' },
      { word: '노력하다', reading: 'noryeokhada', japanese: '努力する', example: '열심히 노력해요.', notes: '動詞' },
      { word: '포기하다', reading: 'pogihada', japanese: '諦める', example: '절대 포기하지 않아요.', notes: '動詞' },
      { word: '도착하다', reading: 'dochakhada', japanese: '到着する', example: '역에 도착했어요.', notes: '動詞' },
      { word: '출발하다', reading: 'chulbalhada', japanese: '出発する', example: '내일 아침에 출발해요.', notes: '動詞' },
      { word: '참가하다', reading: 'chamgahada', japanese: '参加する', example: '행사에 참가했어요.', notes: '動詞' },
      // 中級形容詞
      { word: '중요하다', reading: 'jungyohada', japanese: '重要だ', example: '이 일이 중요해요.', notes: '形容詞' },
      { word: '어렵다', reading: 'eoyreopda', japanese: '難しい', example: '한국어가 어려워요.', notes: '形容詞' },
      { word: '쉽다', reading: 'swipda', japanese: '易しい', example: '이 문제는 쉬워요.', notes: '形容詞' },
      { word: '재미있다', reading: 'jaemiitda', japanese: '面白い', example: '그 책이 재미있어요.', notes: '形容詞' },
      { word: '재미없다', reading: 'jaemieopda', japanese: 'つまらない', example: '그 영화는 재미없어요.', notes: '形容詞' },
      { word: '필요하다', reading: 'piryohada', japanese: '必要だ', example: '도움이 필요해요.', notes: '形容詞' },
      { word: '가능하다', reading: 'ganeunghada', japanese: '可能だ', example: '내일까지 가능해요?', notes: '形容詞' },
      { word: '불가능하다', reading: 'bulganeunghada', japanese: '不可能だ', example: '그건 불가능해요.', notes: '形容詞' },
      { word: '유명하다', reading: 'yumyeonghada', japanese: '有名だ', example: '그 가수가 유명해요.', notes: '形容詞' },
      { word: '특별하다', reading: 'teukbyeolhada', japanese: '特別だ', example: '오늘은 특별한 날이에요.', notes: '形容詞' },
      // 中級名詞
      { word: '문제', reading: 'munje', japanese: '問題', example: '문제를 해결해요.', notes: '名詞' },
      { word: '방법', reading: 'bangbeop', japanese: '方法', example: '좋은 방법이 있어요.', notes: '名詞' },
      { word: '이유', reading: 'iyu', japanese: '理由', example: '이유를 설명해줘요.', notes: '名詞' },
      { word: '기회', reading: 'gihoe', japanese: '機会・チャンス', example: '좋은 기회를 잡아요.', notes: '名詞' },
      { word: '경험', reading: 'gyeongheom', japanese: '経験', example: '좋은 경험이에요.', notes: '名詞' },
      { word: '계획', reading: 'gyehoek', japanese: '計画', example: '여행 계획을 세웠어요.', notes: '名詞' },
      { word: '결과', reading: 'gyeolgwa', japanese: '結果', example: '결과를 기다려요.', notes: '名詞' },
      { word: '원인', reading: 'wonin', japanese: '原因', example: '원인을 찾아야 해요.', notes: '名詞' },
      { word: '목적', reading: 'mokjeok', japanese: '目的', example: '목적이 뭐예요?', notes: '名詞' },
      { word: '내용', reading: 'naeyong', japanese: '内容', example: '내용을 확인해요.', notes: '名詞' },
      { word: '질문', reading: 'jilmun', japanese: '質問', example: '질문이 있어요.', notes: '名詞' },
      { word: '대답', reading: 'daedap', japanese: '答え・返事', example: '대답을 기다려요.', notes: '名詞' },
      { word: '성공', reading: 'seonggong', japanese: '成功', example: '성공을 축하해요!', notes: '名詞' },
      { word: '실패', reading: 'silpae', japanese: '失敗', example: '실패를 두려워하지 마세요.', notes: '名詞' },
      { word: '사랑', reading: 'sarang', japanese: '愛・愛情', example: '사랑해요.', notes: '名詞' },
      { word: '희망', reading: 'huimang', japanese: '希望', example: '희망을 잃지 마세요.', notes: '名詞' },
      { word: '꿈', reading: 'kkum', japanese: '夢', example: '큰 꿈을 가져요.', notes: '名詞' },
    ],
  },

  advanced: {
    label: '上級レベル',
    description: '上級・ビジネス単語（約100語）',
    color: '#1e3a8a',
    words: [
      // ビジネス
      { word: '계약', reading: 'gyeyak', japanese: '契約', example: '계약서에 서명했어요.', notes: 'ビジネス' },
      { word: '협상', reading: 'hyeopsang', japanese: '交渉', example: '가격 협상이 진행 중이에요.', notes: 'ビジネス' },
      { word: '투자', reading: 'tuja', japanese: '投資', example: '해외 투자를 검토하고 있어요.', notes: 'ビジネス' },
      { word: '이익', reading: 'iik', japanese: '利益・利潤', example: '이번 분기에 이익이 증가했어요.', notes: 'ビジネス' },
      { word: '시장', reading: 'sijang', japanese: '市場', example: '새로운 시장을 개척했어요.', notes: 'ビジネス' },
      { word: '경쟁', reading: 'gyeongjaeng', japanese: '競争', example: '치열한 경쟁이 있어요.', notes: 'ビジネス' },
      { word: '발전', reading: 'baljeon', japanese: '発展・発達', example: '기술이 빠르게 발전하고 있어요.', notes: 'ビジネス' },
      { word: '관리', reading: 'gwanri', japanese: '管理', example: '효율적인 관리가 필요해요.', notes: 'ビジネス' },
      { word: '전략', reading: 'jeonnyak', japanese: '戦略', example: '새로운 마케팅 전략을 세웠어요.', notes: 'ビジネス' },
      { word: '효율', reading: 'hyoyul', japanese: '効率', example: '효율을 높여야 해요.', notes: 'ビジネス' },
      { word: '혁신', reading: 'hyeoksin', japanese: 'イノベーション・革新', example: '혁신적인 제품을 개발했어요.', notes: 'ビジネス' },
      { word: '협력', reading: 'hyeomnyeok', japanese: '協力', example: '양사가 협력 관계를 맺었어요.', notes: 'ビジネス' },
      { word: '성과', reading: 'seonggwa', japanese: '成果', example: '좋은 성과를 거뒀어요.', notes: 'ビジネス' },
      { word: '목표', reading: 'mokpyo', japanese: '目標', example: '올해 목표를 달성했어요.', notes: 'ビジネス' },
      { word: '예산', reading: 'yesan', japanese: '予算', example: '예산을 초과했어요.', notes: 'ビジネス' },
      // 社会
      { word: '사회', reading: 'sahoe', japanese: '社会', example: '건강한 사회를 만들어요.', notes: '社会' },
      { word: '정부', reading: 'jeongbu', japanese: '政府', example: '정부가 새 정책을 발표했어요.', notes: '社会' },
      { word: '경제', reading: 'gyeongje', japanese: '経済', example: '경제가 성장하고 있어요.', notes: '社会' },
      { word: '문화', reading: 'munhwa', japanese: '文化', example: '한국 문화에 관심이 있어요.', notes: '社会' },
      { word: '교육', reading: 'gyoyuk', japanese: '教育', example: '교육의 질을 높여야 해요.', notes: '社会' },
      { word: '환경', reading: 'hwangyeong', japanese: '環境', example: '환경 보호가 중요해요.', notes: '社会' },
      { word: '과학기술', reading: 'gwahakgisul', japanese: '科学技術', example: '과학기술이 삶을 바꾸고 있어요.', notes: '社会' },
      { word: '의료', reading: 'uiryo', japanese: '医療', example: '의료 서비스를 개선해야 해요.', notes: '社会' },
      { word: '법률', reading: 'beomnyul', japanese: '法律', example: '법률을 준수해야 해요.', notes: '社会' },
      { word: '정책', reading: 'jeongchaek', japanese: '政策', example: '새 환경 정책이 시행됐어요.', notes: '社会' },
      { word: '민주주의', reading: 'minjujuui', japanese: '民主主義', example: '민주주의 사회에 살고 있어요.', notes: '社会' },
      { word: '인권', reading: 'ingwon', japanese: '人権', example: '인권을 존중해야 해요.', notes: '社会' },
      { word: '복지', reading: 'bokji', japanese: '福祉', example: '사회 복지를 강화해야 해요.', notes: '社会' },
      // 抽象概念
      { word: '자유', reading: 'jayu', japanese: '自由', example: '자유는 소중한 가치예요.', notes: '抽象' },
      { word: '평등', reading: 'pyeongdeung', japanese: '平等', example: '모든 사람은 평등해요.', notes: '抽象' },
      { word: '책임', reading: 'chaegim', japanese: '責任', example: '자신의 행동에 책임을 져야 해요.', notes: '抽象' },
      { word: '의무', reading: 'uimu', japanese: '義務', example: '납세는 국민의 의무예요.', notes: '抽象' },
      { word: '권리', reading: 'gwonri', japanese: '権利', example: '기본 권리를 보장받아야 해요.', notes: '抽象' },
      { word: '도덕', reading: 'dodeok', japanese: '道徳', example: '도덕적 판단이 중요해요.', notes: '抽象' },
      { word: '가치', reading: 'gachi', japanese: '価値', example: '인생의 가치를 생각해요.', notes: '抽象' },
      { word: '의미', reading: 'uimi', japanese: '意味', example: '삶의 의미를 찾아요.', notes: '抽象' },
      { word: '이상', reading: 'isang', japanese: '理想', example: '이상적인 세상을 꿈꿔요.', notes: '抽象' },
      { word: '현실', reading: 'hyeonsil', japanese: '現実', example: '현실을 직시해야 해요.', notes: '抽象' },
      { word: '진실', reading: 'jinsil', japanese: '真実', example: '진실을 말해야 해요.', notes: '抽象' },
      { word: '정의', reading: 'jeongui', japanese: '正義', example: '정의로운 사회를 만들어야 해요.', notes: '抽象' },
      // 高度な動詞
      { word: '실현하다', reading: 'silhyeonhada', japanese: '実現する', example: '꿈을 실현했어요.', notes: '動詞' },
      { word: '창조하다', reading: 'changjohada', japanese: '創造する', example: '새로운 가치를 창조해요.', notes: '動詞' },
      { word: '분석하다', reading: 'bunseokada', japanese: '分析する', example: '데이터를 분석했어요.', notes: '動詞' },
      { word: '평가하다', reading: 'pyeonggahada', japanese: '評価する', example: '성과를 객관적으로 평가해요.', notes: '動詞' },
      { word: '조정하다', reading: 'jojeonghada', japanese: '調整する', example: '일정을 조정해야 해요.', notes: '動詞' },
      { word: '촉진하다', reading: 'chokjinhada', japanese: '促進する', example: '경제 성장을 촉진해요.', notes: '動詞' },
      { word: '영향을 미치다', reading: 'yeonghyangeul michida', japanese: '影響する', example: '환경이 건강에 영향을 미쳐요.', notes: '動詞' },
      { word: '초월하다', reading: 'choworhada', japanese: '超える・超越する', example: '한계를 초월했어요.', notes: '動詞' },
      { word: '실행하다', reading: 'silhaenghada', japanese: '実行する', example: '계획을 실행해요.', notes: '動詞' },
      { word: '극복하다', reading: 'geukbokhada', japanese: '克服する', example: '어려움을 극복했어요.', notes: '動詞' },
      { word: '제안하다', reading: 'jeanhada', japanese: '提案する', example: '새로운 아이디어를 제안했어요.', notes: '動詞' },
      { word: '검토하다', reading: 'geomtohada', japanese: '検討する', example: '방안을 검토하고 있어요.', notes: '動詞' },
      { word: '추진하다', reading: 'chujinhada', japanese: '推進する', example: '프로젝트를 적극적으로 추진해요.', notes: '動詞' },
      { word: '강조하다', reading: 'gangjohada', japanese: '強調する', example: '안전의 중요성을 강조했어요.', notes: '動詞' },
      { word: '구현하다', reading: 'guhyeonhada', japanese: '具現化する・実装する', example: '아이디어를 구현했어요.', notes: '動詞' },
      // 高度な形容詞・名詞
      { word: '지속적', reading: 'jisokjeok', japanese: '持続的な', example: '지속적인 발전이 필요해요.', notes: '形容詞' },
      { word: '효과적', reading: 'hyogwajeok', japanese: '効果的な', example: '효과적인 방법을 찾아요.', notes: '形容詞' },
      { word: '혁신적', reading: 'hyeoksinjeok', japanese: '革新的な', example: '혁신적인 접근이 필요해요.', notes: '形容詞' },
      { word: '체계적', reading: 'chegyejeok', japanese: '体系的な', example: '체계적으로 학습해요.', notes: '形容詞' },
      { word: '창의적', reading: 'changijeok', japanese: '創意的な・クリエイティブな', example: '창의적인 사고가 중요해요.', notes: '形容詞' },
      { word: '적극적', reading: 'jeokgeukjeok', japanese: '積極的な', example: '적극적으로 참여해요.', notes: '形容詞' },
      { word: '객관적', reading: 'gaekgwanjeok', japanese: '客観的な', example: '객관적으로 판단해요.', notes: '形容詞' },
      { word: '주관적', reading: 'jugwanjeok', japanese: '主観的な', example: '주관적인 의견이에요.', notes: '形容詞' },
      { word: '논리적', reading: 'nonnijeok', japanese: '論理的な', example: '논리적으로 설명해요.', notes: '形容詞' },
      { word: '비판적', reading: 'bipanjeok', japanese: '批判的な', example: '비판적 사고가 필요해요.', notes: '形容詞' },
      // 高度な名詞
      { word: '패러다임', reading: 'paereodaim', japanese: 'パラダイム', example: '패러다임이 바뀌고 있어요.', notes: '名詞' },
      { word: '인프라', reading: 'inpeura', japanese: 'インフラ', example: '인프라를 구축해야 해요.', notes: '名詞' },
      { word: '플랫폼', reading: 'peullaetpom', japanese: 'プラットフォーム', example: '디지털 플랫폼을 활용해요.', notes: '名詞' },
      { word: '네트워크', reading: 'neteuwokeu', japanese: 'ネットワーク', example: '인적 네트워크를 넓혀요.', notes: '名詞' },
      { word: '프로세스', reading: 'peuroeseseu', japanese: 'プロセス', example: '업무 프로세스를 개선해요.', notes: '名詞' },
      { word: '시스템', reading: 'siseutem', japanese: 'システム', example: '새로운 시스템을 도입했어요.', notes: '名詞' },
      { word: '데이터', reading: 'deiteo', japanese: 'データ', example: '데이터를 기반으로 결정해요.', notes: '名詞' },
      { word: '알고리즘', reading: 'algolijeum', japanese: 'アルゴリズム', example: '효율적인 알고리즘을 개발했어요.', notes: '名詞' },
      { word: '인공지능', reading: 'ingongjinung', japanese: '人工知能・AI', example: '인공지능이 발전하고 있어요.', notes: '名詞' },
      { word: '지속가능성', reading: 'jisokganeungseong', japanese: '持続可能性', example: '지속가능성을 고려해야 해요.', notes: '名詞' },
      { word: '다양성', reading: 'dayangseong', japanese: '多様性', example: '다양성을 존중해야 해요.', notes: '名詞' },
      { word: '투명성', reading: 'tumyeongseong', japanese: '透明性', example: '정보의 투명성이 중요해요.', notes: '名詞' },
      { word: '신뢰성', reading: 'sinnoeeseong', japanese: '信頼性', example: '시스템의 신뢰성을 높여요.', notes: '名詞' },
    ],
  },
};
