/* ===================================================
   ドイツ語学習アプリ  words-data.js
   =================================================== */

const WORD_SETS = {
  beginner: {
    label: '初級レベル',
    description: '日常会話の基本単語（約100語）',
    color: '#d97706',
    words: [
      // 挨拶
      { word: 'Hallo', japanese: 'こんにちは', example: 'Hallo! Wie geht es Ihnen?', notes: '挨拶' },
      { word: 'Guten Morgen', japanese: 'おはようございます', example: 'Guten Morgen! Haben Sie gut geschlafen?', notes: '挨拶' },
      { word: 'Guten Tag', japanese: 'こんにちは（フォーマル）', example: 'Guten Tag, Herr Müller!', notes: '挨拶' },
      { word: 'Guten Abend', japanese: 'こんばんは', example: 'Guten Abend! Wie war Ihr Tag?', notes: '挨拶' },
      { word: 'Gute Nacht', japanese: 'おやすみなさい', example: 'Gute Nacht! Schlaf gut!', notes: '挨拶' },
      { word: 'Auf Wiedersehen', japanese: 'さようなら', example: 'Auf Wiedersehen! Bis bald!', notes: '挨拶' },
      { word: 'Tschüss', japanese: 'またね', example: 'Tschüss! Bis morgen!', notes: '挨拶（カジュアル）' },
      { word: 'Danke', japanese: 'ありがとう', example: 'Danke für Ihre Hilfe!', notes: '挨拶' },
      { word: 'Danke schön', japanese: 'どうもありがとう', example: 'Danke schön für das Geschenk!', notes: '挨拶' },
      { word: 'Bitte', japanese: 'お願いします・どういたしまして', example: 'Ein Kaffee, bitte.', notes: '礼儀' },
      { word: 'Entschuldigung', japanese: 'すみません', example: 'Entschuldigung, wo ist die Toilette?', notes: '挨拶' },
      { word: 'Es tut mir leid', japanese: 'ごめんなさい', example: 'Es tut mir leid, ich komme zu spät.', notes: '挨拶' },
      { word: 'Ja', japanese: 'はい', example: 'Ja, ich verstehe.', notes: '基本表現' },
      { word: 'Nein', japanese: 'いいえ', example: 'Nein, danke.', notes: '基本表現' },
      { word: 'Vielleicht', japanese: 'たぶん', example: 'Vielleicht komme ich morgen.', notes: '基本表現' },
      { word: 'Natürlich', japanese: 'もちろん', example: 'Natürlich helfe ich dir!', notes: '基本表現' },
      // 人称
      { word: 'ich', japanese: '私', example: 'Ich bin Student.', notes: '人称代名詞' },
      { word: 'du', japanese: 'あなた', example: 'Bist du müde?', notes: '人称代名詞' },
      { word: 'er', japanese: '彼', example: 'Er arbeitet in Berlin.', notes: '人称代名詞' },
      { word: 'sie', japanese: '彼女・彼女ら', example: 'Sie ist sehr nett.', notes: '人称代名詞' },
      { word: 'es', japanese: 'それ', example: 'Es ist kalt heute.', notes: '人称代名詞' },
      { word: 'wir', japanese: '私たち', example: 'Wir gehen ins Kino.', notes: '人称代名詞' },
      { word: 'ihr', japanese: 'あなたたち', example: 'Seid ihr fertig?', notes: '人称代名詞' },
      { word: 'Sie', japanese: 'あなた（敬語）', example: 'Wie heißen Sie?', notes: '敬称代名詞' },
      // 基本動詞
      { word: 'sein', japanese: '〜である', example: 'Ich bin Student.', notes: '基本動詞' },
      { word: 'haben', japanese: '持っている', example: 'Ich habe eine Katze.', notes: '基本動詞' },
      { word: 'gehen', japanese: '行く', example: 'Ich gehe zur Schule.', notes: '動詞' },
      { word: 'kommen', japanese: '来る', example: 'Er kommt aus Japan.', notes: '動詞' },
      { word: 'machen', japanese: 'する・作る', example: 'Was machst du heute?', notes: '動詞' },
      { word: 'sagen', japanese: '言う', example: 'Was hast du gesagt?', notes: '動詞' },
      { word: 'sehen', japanese: '見る', example: 'Ich sehe einen Film.', notes: '動詞' },
      { word: 'wissen', japanese: '知っている', example: 'Ich weiß es nicht.', notes: '動詞' },
      { word: 'können', japanese: 'できる', example: 'Ich kann Deutsch sprechen.', notes: '助動詞' },
      { word: 'wollen', japanese: '欲しい・したい', example: 'Ich will Kaffee trinken.', notes: '助動詞' },
      { word: 'müssen', japanese: '〜しなければならない', example: 'Ich muss arbeiten.', notes: '助動詞' },
      { word: 'essen', japanese: '食べる', example: 'Ich esse einen Apfel.', notes: '動詞' },
      { word: 'trinken', japanese: '飲む', example: 'Er trinkt Wasser.', notes: '動詞' },
      { word: 'schlafen', japanese: '眠る', example: 'Ich schlafe acht Stunden.', notes: '動詞' },
      { word: 'sprechen', japanese: '話す', example: 'Sie spricht Englisch.', notes: '動詞' },
      { word: 'hören', japanese: '聴く', example: 'Ich höre Musik.', notes: '動詞' },
      { word: 'lesen', japanese: '読む', example: 'Er liest ein Buch.', notes: '動詞' },
      { word: 'schreiben', japanese: '書く', example: 'Ich schreibe einen Brief.', notes: '動詞' },
      { word: 'lernen', japanese: '学ぶ', example: 'Sie lernt Deutsch.', notes: '動詞' },
      { word: 'mögen', japanese: '好きだ', example: 'Ich mag Schokolade.', notes: '動詞' },
      { word: 'arbeiten', japanese: '働く', example: 'Er arbeitet bei BMW.', notes: '動詞' },
      { word: 'kaufen', japanese: '買う', example: 'Ich kaufe Brot im Supermarkt.', notes: '動詞' },
      { word: 'helfen', japanese: '手伝う', example: 'Kannst du mir helfen?', notes: '動詞' },
      // 家族
      { word: 'Familie', japanese: '家族', example: 'Meine Familie ist groß.', notes: '名詞(女性)' },
      { word: 'Vater', japanese: '父', example: 'Mein Vater arbeitet als Arzt.', notes: '名詞(男性)' },
      { word: 'Mutter', japanese: '母', example: 'Meine Mutter kocht gern.', notes: '名詞(女性)' },
      { word: 'Bruder', japanese: '兄・弟', example: 'Mein Bruder ist 10 Jahre alt.', notes: '名詞(男性)' },
      { word: 'Schwester', japanese: '姉・妹', example: 'Meine Schwester studiert in München.', notes: '名詞(女性)' },
      { word: 'Kind', japanese: '子供', example: 'Das Kind spielt im Park.', notes: '名詞(中性)' },
      { word: 'Mann', japanese: '夫・男性', example: 'Mein Mann ist sehr nett.', notes: '名詞(男性)' },
      { word: 'Frau', japanese: '妻・女性', example: 'Meine Frau arbeitet als Lehrerin.', notes: '名詞(女性)' },
      { word: 'Freund', japanese: '友達（男性）', example: 'Er ist mein bester Freund.', notes: '名詞(男性)' },
      { word: 'Freundin', japanese: '友達（女性）', example: 'Sie ist meine beste Freundin.', notes: '名詞(女性)' },
      // 場所
      { word: 'Schule', japanese: '学校', example: 'Ich gehe jeden Tag zur Schule.', notes: '名詞(女性)' },
      { word: 'Haus', japanese: '家', example: 'Ich gehe nach Hause.', notes: '名詞(中性)' },
      { word: 'Büro', japanese: 'オフィス', example: 'Er arbeitet im Büro.', notes: '名詞(中性)' },
      { word: 'Krankenhaus', japanese: '病院', example: 'Das Krankenhaus ist in der Nähe.', notes: '名詞(中性)' },
      { word: 'Bank', japanese: '銀行', example: 'Ich gehe zur Bank.', notes: '名詞(女性)' },
      { word: 'Supermarkt', japanese: 'スーパー', example: 'Ich kaufe im Supermarkt ein.', notes: '名詞(男性)' },
      { word: 'Restaurant', japanese: 'レストラン', example: 'Wir essen im Restaurant.', notes: '名詞(中性)' },
      { word: 'Bibliothek', japanese: '図書館', example: 'Ich lese in der Bibliothek.', notes: '名詞(女性)' },
      { word: 'Park', japanese: '公園', example: 'Wir spielen im Park.', notes: '名詞(男性)' },
      { word: 'Bahnhof', japanese: '駅', example: 'Der Zug fährt vom Bahnhof ab.', notes: '名詞(男性)' },
      { word: 'Flughafen', japanese: '空港', example: 'Das Flugzeug landet am Flughafen.', notes: '名詞(男性)' },
      { word: 'Hotel', japanese: 'ホテル', example: 'Wir übernachten im Hotel.', notes: '名詞(中性)' },
      { word: 'Kirche', japanese: '教会', example: 'Die Kirche ist sehr alt.', notes: '名詞(女性)' },
      // 食べ物
      { word: 'Brot', japanese: 'パン', example: 'Ich esse Brot zum Frühstück.', notes: '名詞(中性)' },
      { word: 'Käse', japanese: 'チーズ', example: 'Dieser Käse schmeckt gut.', notes: '名詞(男性)' },
      { word: 'Wurst', japanese: 'ソーセージ', example: 'Deutsche Wurst ist sehr lecker.', notes: '名詞(女性)' },
      { word: 'Bier', japanese: 'ビール', example: 'Deutsches Bier ist weltberühmt.', notes: '名詞(中性)' },
      { word: 'Wasser', japanese: '水', example: 'Ich trinke viel Wasser.', notes: '名詞(中性)' },
      { word: 'Kaffee', japanese: 'コーヒー', example: 'Ich trinke morgens Kaffee.', notes: '名詞(男性)' },
      { word: 'Tee', japanese: 'お茶', example: 'Sie trinkt lieber Tee als Kaffee.', notes: '名詞(男性)' },
      { word: 'Fleisch', japanese: '肉', example: 'Er isst gern Fleisch.', notes: '名詞(中性)' },
      { word: 'Fisch', japanese: '魚', example: 'Fisch ist gesund.', notes: '名詞(男性)' },
      { word: 'Gemüse', japanese: '野菜', example: 'Ich esse viel Gemüse.', notes: '名詞(中性)' },
      { word: 'Obst', japanese: '果物', example: 'Obst ist reich an Vitaminen.', notes: '名詞(中性)' },
      { word: 'Kuchen', japanese: 'ケーキ', example: 'Zum Geburtstag gibt es Kuchen.', notes: '名詞(男性)' },
      // 数字
      { word: 'eins', japanese: '1', example: 'Ich habe eins bekommen.', notes: '数字' },
      { word: 'zwei', japanese: '2', example: 'Ich brauche zwei Brötchen.', notes: '数字' },
      { word: 'drei', japanese: '3', example: 'Wir sind drei Personen.', notes: '数字' },
      { word: 'vier', japanese: '4', example: 'Das kostet vier Euro.', notes: '数字' },
      { word: 'fünf', japanese: '5', example: 'In fünf Minuten bin ich da.', notes: '数字' },
      { word: 'sechs', japanese: '6', example: 'Um sechs Uhr esse ich zu Abend.', notes: '数字' },
      { word: 'sieben', japanese: '7', example: 'Die Woche hat sieben Tage.', notes: '数字' },
      { word: 'acht', japanese: '8', example: 'Ich schlafe acht Stunden.', notes: '数字' },
      { word: 'neun', japanese: '9', example: 'Es ist neun Uhr.', notes: '数字' },
      { word: 'zehn', japanese: '10', example: 'Ich habe zehn Euro.', notes: '数字' },
      { word: 'hundert', japanese: '百', example: 'Das kostet hundert Euro.', notes: '数字' },
      { word: 'tausend', japanese: '千', example: 'Das Auto kostet tausend Euro.', notes: '数字' },
      // 時間
      { word: 'heute', japanese: '今日', example: 'Heute ist Montag.', notes: '時間' },
      { word: 'morgen', japanese: '明日', example: 'Morgen fahre ich nach Berlin.', notes: '時間' },
      { word: 'gestern', japanese: '昨日', example: 'Gestern war ich krank.', notes: '時間' },
      { word: 'jetzt', japanese: '今', example: 'Ich bin jetzt zu Hause.', notes: '時間' },
      { word: 'früher', japanese: '以前', example: 'Früher wohnte ich in Hamburg.', notes: '時間' },
      { word: 'später', japanese: '後で', example: 'Wir sehen uns später.', notes: '時間' },
      { word: 'Morgen', japanese: '朝', example: 'Am Morgen trinke ich Kaffee.', notes: '名詞(男性)・時間' },
      { word: 'Nachmittag', japanese: '午後', example: 'Am Nachmittag lerne ich Deutsch.', notes: '名詞(男性)・時間' },
      { word: 'Abend', japanese: '夜', example: 'Am Abend sehe ich fern.', notes: '名詞(男性)・時間' },
      { word: 'Woche', japanese: '週', example: 'Diese Woche bin ich sehr beschäftigt.', notes: '名詞(女性)' },
      { word: 'Monat', japanese: '月', example: 'Im nächsten Monat fahre ich in Urlaub.', notes: '名詞(男性)' },
      { word: 'Jahr', japanese: '年', example: 'Das neue Jahr beginnt bald.', notes: '名詞(中性)' },
      // 形容詞
      { word: 'groß', japanese: '大きい', example: 'Berlin ist eine große Stadt.', notes: '形容詞' },
      { word: 'klein', japanese: '小さい', example: 'Das Kind ist noch klein.', notes: '形容詞' },
      { word: 'schön', japanese: '美しい', example: 'Das Wetter ist heute schön.', notes: '形容詞' },
      { word: 'neu', japanese: '新しい', example: 'Ich habe ein neues Auto.', notes: '形容詞' },
      { word: 'alt', japanese: '古い', example: 'Das ist ein altes Buch.', notes: '形容詞' },
      { word: 'gut', japanese: '良い', example: 'Das Essen ist sehr gut.', notes: '形容詞' },
      { word: 'schlecht', japanese: '悪い', example: 'Das Wetter ist schlecht heute.', notes: '形容詞' },
      { word: 'teuer', japanese: '高い', example: 'Das Hotel ist sehr teuer.', notes: '形容詞' },
      { word: 'günstig', japanese: '安い', example: 'Das Restaurant ist sehr günstig.', notes: '形容詞' },
      { word: 'schnell', japanese: '速い', example: 'Der Zug fährt sehr schnell.', notes: '形容詞' },
      { word: 'langsam', japanese: '遅い', example: 'Das Auto fährt langsam.', notes: '形容詞' },
      { word: 'glücklich', japanese: '幸せ', example: 'Ich bin sehr glücklich.', notes: '形容詞' },
      { word: 'traurig', japanese: '悲しい', example: 'Er ist sehr traurig.', notes: '形容詞' },
      { word: 'müde', japanese: '疲れた', example: 'Ich bin sehr müde.', notes: '形容詞' },
      { word: 'beschäftigt', japanese: '忙しい', example: 'Sie ist sehr beschäftigt.', notes: '形容詞' },
      { word: 'heiß', japanese: '暑い', example: 'Es ist heute sehr heiß.', notes: '形容詞' },
      { word: 'kalt', japanese: '寒い', example: 'Im Winter ist es kalt.', notes: '形容詞' },
      // 色
      { word: 'rot', japanese: '赤', example: 'Die Rose ist rot.', notes: '色' },
      { word: 'blau', japanese: '青', example: 'Der Himmel ist blau.', notes: '色' },
      { word: 'grün', japanese: '緑', example: 'Das Gras ist grün.', notes: '色' },
      { word: 'gelb', japanese: '黄', example: 'Die Sonne ist gelb.', notes: '色' },
      { word: 'weiß', japanese: '白', example: 'Der Schnee ist weiß.', notes: '色' },
      { word: 'schwarz', japanese: '黒', example: 'Die Nacht ist schwarz.', notes: '色' },
      { word: 'rosa', japanese: 'ピンク', example: 'Die Blumen sind rosa.', notes: '色' },
      { word: 'lila', japanese: '紫', example: 'Sie trägt ein lila Kleid.', notes: '色' },
      { word: 'orange', japanese: 'オレンジ', example: 'Die Orange ist orange.', notes: '色' },
      { word: 'grau', japanese: 'グレー', example: 'Der Himmel ist grau.', notes: '色' },
      // 曜日
      { word: 'Montag', japanese: '月曜日', example: 'Am Montag gehe ich zur Arbeit.', notes: '名詞(男性)・曜日' },
      { word: 'Dienstag', japanese: '火曜日', example: 'Dienstag haben wir Sport.', notes: '名詞(男性)・曜日' },
      { word: 'Mittwoch', japanese: '水曜日', example: 'Am Mittwoch lerne ich Deutsch.', notes: '名詞(男性)・曜日' },
      { word: 'Donnerstag', japanese: '木曜日', example: 'Donnerstag gehe ich einkaufen.', notes: '名詞(男性)・曜日' },
      { word: 'Freitag', japanese: '金曜日', example: 'Freitag ist mein Lieblingstag.', notes: '名詞(男性)・曜日' },
      { word: 'Samstag', japanese: '土曜日', example: 'Am Samstag schlafe ich lange.', notes: '名詞(男性)・曜日' },
      { word: 'Sonntag', japanese: '日曜日', example: 'Sonntag ist ein freier Tag.', notes: '名詞(男性)・曜日' },
    ]
  },
  intermediate: {
    label: '中級レベル',
    description: '中級会話の単語（約100語）',
    color: '#b45309',
    words: [
      // 職業
      { word: 'Lehrer / Lehrerin', japanese: '先生', example: 'Der Lehrer erklärt die Grammatik.', notes: '職業' },
      { word: 'Arzt / Ärztin', japanese: '医者', example: 'Der Arzt untersucht den Patienten.', notes: '職業' },
      { word: 'Ingenieur', japanese: 'エンジニア', example: 'Er arbeitet als Ingenieur bei Siemens.', notes: '職業(男性)' },
      { word: 'Rechtsanwalt', japanese: '弁護士', example: 'Sie ist Rechtsanwältin.', notes: '職業(男性)' },
      { word: 'Krankenschwester', japanese: '看護師', example: 'Die Krankenschwester hilft dem Patienten.', notes: '職業(女性)' },
      { word: 'Fahrer', japanese: '運転手', example: 'Der Fahrer kennt die Stadt gut.', notes: '職業(男性)' },
      { word: 'Koch / Köchin', japanese: '料理人', example: 'Der Koch bereitet das Essen zu.', notes: '職業' },
      { word: 'Journalist', japanese: '記者', example: 'Der Journalist schreibt einen Artikel.', notes: '職業(男性)' },
      { word: 'Polizist', japanese: '警察', example: 'Der Polizist regelt den Verkehr.', notes: '職業(男性)' },
      { word: 'Geschäftsmann', japanese: 'ビジネスマン', example: 'Er ist ein erfolgreicher Geschäftsmann.', notes: '職業(男性)' },
      // 交通
      { word: 'Auto', japanese: '車', example: 'Ich fahre jeden Tag mit dem Auto.', notes: '名詞(中性)' },
      { word: 'Zug', japanese: '電車', example: 'Der Zug fährt nach Berlin.', notes: '名詞(男性)' },
      { word: 'Bus', japanese: 'バス', example: 'Ich nehme den Bus zur Arbeit.', notes: '名詞(男性)' },
      { word: 'U-Bahn', japanese: '地下鉄', example: 'In Berlin gibt es viele U-Bahn-Linien.', notes: '名詞(女性)' },
      { word: 'Flugzeug', japanese: '飛行機', example: 'Das Flugzeug fliegt nach Tokyo.', notes: '名詞(中性)' },
      { word: 'Taxi', japanese: 'タクシー', example: 'Ich nehme ein Taxi zum Flughafen.', notes: '名詞(中性)' },
      { word: 'Fahrrad', japanese: '自転車', example: 'Er fährt mit dem Fahrrad zur Schule.', notes: '名詞(中性)' },
      { word: 'Schiff', japanese: '船', example: 'Das Schiff fährt über den Rhein.', notes: '名詞(中性)' },
      // 天気
      { word: 'Wetter', japanese: '天気', example: 'Das Wetter ist heute schön.', notes: '名詞(中性)' },
      { word: 'Sonne', japanese: '太陽・晴れ', example: 'Die Sonne scheint heute.', notes: '名詞(女性)' },
      { word: 'Regen', japanese: '雨', example: 'Es gibt heute Regen.', notes: '名詞(男性)' },
      { word: 'Schnee', japanese: '雪', example: 'Im Winter fällt Schnee.', notes: '名詞(男性)' },
      { word: 'Wind', japanese: '風', example: 'Heute weht ein starker Wind.', notes: '名詞(男性)' },
      { word: 'Wolke', japanese: '雲', example: 'Die Wolken sind grau.', notes: '名詞(女性)' },
      { word: 'Temperatur', japanese: '温度', example: 'Die Temperatur beträgt 20 Grad.', notes: '名詞(女性)' },
      { word: 'Jahreszeit', japanese: '季節', example: 'Was ist deine Lieblingsjahreszeit?', notes: '名詞(女性)' },
      { word: 'Frühling', japanese: '春', example: 'Im Frühling blühen die Blumen.', notes: '名詞(男性)' },
      { word: 'Sommer', japanese: '夏', example: 'Im Sommer fahren wir ans Meer.', notes: '名詞(男性)' },
      { word: 'Herbst', japanese: '秋', example: 'Im Herbst fallen die Blätter.', notes: '名詞(男性)' },
      { word: 'Winter', japanese: '冬', example: 'Im Winter ist es kalt.', notes: '名詞(男性)' },
      // 感情
      { word: 'froh', japanese: '嬉しい', example: 'Ich bin froh, dich zu sehen.', notes: '形容詞' },
      { word: 'wütend', japanese: '怒っている', example: 'Er ist sehr wütend.', notes: '形容詞' },
      { word: 'besorgt', japanese: '心配している', example: 'Sie ist sehr besorgt um ihren Sohn.', notes: '形容詞' },
      { word: 'aufgeregt', japanese: '興奮している', example: 'Das Kind ist sehr aufgeregt.', notes: '形容詞' },
      { word: 'verlegen', japanese: '恥ずかしい', example: 'Er ist verlegen geworden.', notes: '形容詞' },
      { word: 'nervös', japanese: '緊張している', example: 'Sie ist vor dem Examen nervös.', notes: '形容詞' },
      { word: 'entspannt', japanese: 'リラックスした', example: 'Am Wochenende bin ich entspannt.', notes: '形容詞' },
      { word: 'überrascht', japanese: '驚いた', example: 'Ich bin überrascht von der Nachricht.', notes: '形容詞' },
      // 動詞
      { word: 'beginnen', japanese: '始める', example: 'Der Unterricht beginnt um 9 Uhr.', notes: '動詞' },
      { word: 'beenden', japanese: '終える', example: 'Ich muss die Arbeit beenden.', notes: '動詞' },
      { word: 'vorbereiten', japanese: '準備する', example: 'Ich bereite das Abendessen vor.', notes: '動詞' },
      { word: 'entscheiden', japanese: '決める', example: 'Wir müssen uns entscheiden.', notes: '動詞' },
      { word: 'glauben', japanese: '信じる', example: 'Ich glaube dir nicht.', notes: '動詞' },
      { word: 'verstehen', japanese: '理解する', example: 'Ich verstehe die Frage nicht.', notes: '動詞' },
      { word: 'lösen', japanese: '解決する', example: 'Wir müssen das Problem lösen.', notes: '動詞' },
      { word: 'entdecken', japanese: '発見する', example: 'Er hat Amerika entdeckt.', notes: '動詞' },
      { word: 'ändern', japanese: '変える', example: 'Ich möchte mein Leben ändern.', notes: '動詞' },
      { word: 'reisen', japanese: '旅行する', example: 'Ich reise gern durch Europa.', notes: '動詞' },
      { word: 'treffen', japanese: '会う', example: 'Wir treffen uns um 3 Uhr.', notes: '動詞' },
      { word: 'vorstellen', japanese: '紹介する', example: 'Darf ich mich vorstellen?', notes: '動詞' },
      { word: 'erklären', japanese: '説明する', example: 'Können Sie das erklären?', notes: '動詞' },
      { word: 'anrufen', japanese: '電話する', example: 'Ich rufe dich morgen an.', notes: '動詞(分離)' },
      { word: 'einladen', japanese: '招待する', example: 'Ich lade dich zum Abendessen ein.', notes: '動詞(分離)' },
      { word: 'aufhören', japanese: '止める・やめる', example: 'Hör bitte auf damit!', notes: '動詞(分離)' },
      { word: 'verbringen', japanese: '過ごす', example: 'Ich verbringe den Urlaub in Italien.', notes: '動詞' },
      { word: 'vermissen', japanese: '恋しく思う', example: 'Ich vermisse meine Familie sehr.', notes: '動詞' },
      { word: 'versuchen', japanese: '試みる', example: 'Ich versuche, Deutsch zu lernen.', notes: '動詞' },
      // 形容詞
      { word: 'wichtig', japanese: '重要な', example: 'Das ist eine wichtige Entscheidung.', notes: '形容詞' },
      { word: 'interessant', japanese: '面白い', example: 'Das Buch ist sehr interessant.', notes: '形容詞' },
      { word: 'langweilig', japanese: '退屈な', example: 'Der Film war langweilig.', notes: '形容詞' },
      { word: 'kompliziert', japanese: '複雑な', example: 'Die Grammatik ist kompliziert.', notes: '形容詞' },
      { word: 'einfach', japanese: '簡単な', example: 'Das ist einfach!', notes: '形容詞' },
      { word: 'schwierig', japanese: '難しい', example: 'Die Prüfung war schwierig.', notes: '形容詞' },
      { word: 'gefährlich', japanese: '危険な', example: 'Das ist gefährlich!', notes: '形容詞' },
      { word: 'sicher', japanese: '安全な', example: 'Dieser Weg ist sicher.', notes: '形容詞' },
      { word: 'gesund', japanese: '健康な', example: 'Sport ist gesund.', notes: '形容詞' },
      { word: 'klug', japanese: '賢い', example: 'Sie ist ein kluges Mädchen.', notes: '形容詞' },
      { word: 'freundlich', japanese: '親切な', example: 'Er ist sehr freundlich.', notes: '形容詞' },
      { word: 'höflich', japanese: '礼儀正しい', example: 'Sei bitte höflich!', notes: '形容詞' },
      // 名詞・その他
      { word: 'Nachricht', japanese: 'ニュース・メッセージ', example: 'Ich habe eine wichtige Nachricht.', notes: '名詞(女性)' },
      { word: 'Meinung', japanese: '意見', example: 'Was ist deine Meinung dazu?', notes: '名詞(女性)' },
      { word: 'Erfahrung', japanese: '経験', example: 'Ich habe viel Erfahrung.', notes: '名詞(女性)' },
      { word: 'Möglichkeit', japanese: '可能性', example: 'Es gibt viele Möglichkeiten.', notes: '名詞(女性)' },
      { word: 'Verhältnis', japanese: '関係', example: 'Wir haben ein gutes Verhältnis.', notes: '名詞(中性)' },
      { word: 'Gelegenheit', japanese: '機会', example: 'Das ist eine gute Gelegenheit.', notes: '名詞(女性)' },
      { word: 'Entscheidung', japanese: '決断', example: 'Das war eine schwierige Entscheidung.', notes: '名詞(女性)' },
      { word: 'Gespräch', japanese: '会話', example: 'Wir hatten ein langes Gespräch.', notes: '名詞(中性)' },
      { word: 'Vorschlag', japanese: '提案', example: 'Ich habe einen Vorschlag.', notes: '名詞(男性)' },
      { word: 'Ergebnis', japanese: '結果', example: 'Das Ergebnis ist positiv.', notes: '名詞(中性)' },
      // 接続詞・副詞
      { word: 'deshalb', japanese: 'だから', example: 'Es regnet, deshalb bleibe ich zu Hause.', notes: '接続詞' },
      { word: 'obwohl', japanese: 'だけれども', example: 'Obwohl es regnet, gehe ich spazieren.', notes: '接続詞' },
      { word: 'trotzdem', japanese: 'それにもかかわらず', example: 'Es regnet, trotzdem gehe ich.', notes: '副詞' },
      { word: 'außerdem', japanese: 'さらに・その上', example: 'Außerdem spreche ich Französisch.', notes: '副詞' },
      { word: 'schließlich', japanese: '最終的に', example: 'Schließlich hat er ja gesagt.', notes: '副詞' },
      { word: 'übrigens', japanese: 'ところで', example: 'Übrigens, wie heißt du?', notes: '副詞' },
      { word: 'ungefähr', japanese: 'おおよそ', example: 'Das kostet ungefähr 50 Euro.', notes: '副詞' },
      { word: 'bereits', japanese: 'すでに', example: 'Ich habe das bereits gemacht.', notes: '副詞' },
      { word: 'noch', japanese: 'まだ・さらに', example: 'Ich lerne noch Deutsch.', notes: '副詞' },
      { word: 'schon', japanese: 'もう・すでに', example: 'Bist du schon fertig?', notes: '副詞' },
    ]
  },
  advanced: {
    label: '上級レベル',
    description: '上級・ビジネス単語（約100語）',
    color: '#92400e',
    words: [
      // ビジネス
      { word: 'Vertrag', japanese: '契約', example: 'Wir haben einen Vertrag unterzeichnet.', notes: '名詞(男性)・ビジネス' },
      { word: 'Verhandlung', japanese: '交渉', example: 'Die Verhandlung war erfolgreich.', notes: '名詞(女性)・ビジネス' },
      { word: 'Investition', japanese: '投資', example: 'Das ist eine gute Investition.', notes: '名詞(女性)・ビジネス' },
      { word: 'Gewinn', japanese: '利益', example: 'Das Unternehmen macht Gewinn.', notes: '名詞(男性)・ビジネス' },
      { word: 'Markt', japanese: '市場', example: 'Der europäische Markt wächst.', notes: '名詞(男性)・ビジネス' },
      { word: 'Wettbewerb', japanese: '競争', example: 'Der Wettbewerb ist sehr stark.', notes: '名詞(男性)・ビジネス' },
      { word: 'Entwicklung', japanese: '発展・開発', example: 'Die Entwicklung geht schnell voran.', notes: '名詞(女性)・ビジネス' },
      { word: 'Verwaltung', japanese: '管理・行政', example: 'Die Verwaltung ist komplex.', notes: '名詞(女性)・ビジネス' },
      { word: 'Strategie', japanese: '戦略', example: 'Wir brauchen eine neue Strategie.', notes: '名詞(女性)・ビジネス' },
      { word: 'Effizienz', japanese: '効率', example: 'Die Effizienz muss verbessert werden.', notes: '名詞(女性)・ビジネス' },
      { word: 'Umsatz', japanese: '売上', example: 'Der Umsatz ist gestiegen.', notes: '名詞(男性)・ビジネス' },
      { word: 'Kapital', japanese: '資本', example: 'Wir brauchen mehr Kapital.', notes: '名詞(中性)・ビジネス' },
      { word: 'Haushalt', japanese: '予算・家計', example: 'Der Haushalt muss überarbeitet werden.', notes: '名詞(男性)・ビジネス' },
      { word: 'Kooperation', japanese: '協力', example: 'Die Kooperation ist sehr wichtig.', notes: '名詞(女性)・ビジネス' },
      // 社会
      { word: 'Gesellschaft', japanese: '社会', example: 'Die moderne Gesellschaft verändert sich.', notes: '名詞(女性)・社会' },
      { word: 'Regierung', japanese: '政府', example: 'Die Regierung hat neue Gesetze erlassen.', notes: '名詞(女性)・社会' },
      { word: 'Wirtschaft', japanese: '経済', example: 'Die Wirtschaft wächst langsam.', notes: '名詞(女性)・社会' },
      { word: 'Kultur', japanese: '文化', example: 'Die deutsche Kultur ist reich.', notes: '名詞(女性)・社会' },
      { word: 'Bildung', japanese: '教育', example: 'Bildung ist sehr wichtig.', notes: '名詞(女性)・社会' },
      { word: 'Umwelt', japanese: '環境', example: 'Wir müssen die Umwelt schützen.', notes: '名詞(女性)・社会' },
      { word: 'Technologie', japanese: '科学技術', example: 'Die Technologie entwickelt sich schnell.', notes: '名詞(女性)・社会' },
      { word: 'Gesundheitswesen', japanese: '医療', example: 'Das Gesundheitswesen braucht Reformen.', notes: '名詞(中性)・社会' },
      { word: 'Gesetz', japanese: '法律', example: 'Das Gesetz muss eingehalten werden.', notes: '名詞(中性)・社会' },
      { word: 'Politik', japanese: '政策・政治', example: 'Politik interessiert mich sehr.', notes: '名詞(女性)・社会' },
      { word: 'Demokratie', japanese: '民主主義', example: 'Die Demokratie ist grundlegend.', notes: '名詞(女性)・社会' },
      { word: 'Globalisierung', japanese: 'グローバル化', example: 'Die Globalisierung hat viele Auswirkungen.', notes: '名詞(女性)・社会' },
      // 抽象概念
      { word: 'Freiheit', japanese: '自由', example: 'Freiheit ist ein Grundrecht.', notes: '名詞(女性)・抽象' },
      { word: 'Gleichheit', japanese: '平等', example: 'Gleichheit ist ein wichtiger Wert.', notes: '名詞(女性)・抽象' },
      { word: 'Verantwortung', japanese: '責任', example: 'Jeder trägt Verantwortung.', notes: '名詞(女性)・抽象' },
      { word: 'Pflicht', japanese: '義務', example: 'Es ist meine Pflicht zu helfen.', notes: '名詞(女性)・抽象' },
      { word: 'Recht', japanese: '権利', example: 'Jeder hat das Recht auf Bildung.', notes: '名詞(中性)・抽象' },
      { word: 'Moral', japanese: '道徳', example: 'Moral spielt eine wichtige Rolle.', notes: '名詞(女性)・抽象' },
      { word: 'Wert', japanese: '価値', example: 'Was sind deine persönlichen Werte?', notes: '名詞(男性)・抽象' },
      { word: 'Bedeutung', japanese: '意味', example: 'Was ist die Bedeutung dieses Wortes?', notes: '名詞(女性)・抽象' },
      { word: 'Ziel', japanese: '目標', example: 'Ich habe mein Ziel erreicht.', notes: '名詞(中性)・抽象' },
      { word: 'Ideal', japanese: '理想', example: 'Wir streben nach einem Ideal.', notes: '名詞(中性)・抽象' },
      { word: 'Wahrheit', japanese: '真実', example: 'Die Wahrheit ist oft komplex.', notes: '名詞(女性)・抽象' },
      { word: 'Gerechtigkeit', japanese: '正義', example: 'Gerechtigkeit ist ein hohes Gut.', notes: '名詞(女性)・抽象' },
      { word: 'Bewusstsein', japanese: '意識・認識', example: 'Das Bewusstsein für Umweltprobleme wächst.', notes: '名詞(中性)・抽象' },
      { word: 'Prinzip', japanese: '原則', example: 'Ich handle nach meinen Prinzipien.', notes: '名詞(中性)・抽象' },
      // 高度動詞
      { word: 'verwirklichen', japanese: '実現する', example: 'Er hat seinen Traum verwirklicht.', notes: '動詞' },
      { word: 'erschaffen', japanese: '創造する', example: 'Der Künstler erschafft neue Werke.', notes: '動詞' },
      { word: 'analysieren', japanese: '分析する', example: 'Wir müssen die Daten analysieren.', notes: '動詞' },
      { word: 'bewerten', japanese: '評価する', example: 'Wie würden Sie das bewerten?', notes: '動詞' },
      { word: 'koordinieren', japanese: '調整する', example: 'Er koordiniert das Projekt.', notes: '動詞' },
      { word: 'fördern', japanese: '促進する', example: 'Wir müssen die Bildung fördern.', notes: '動詞' },
      { word: 'beeinflussen', japanese: '影響する', example: 'Das beeinflusst meine Entscheidung.', notes: '動詞' },
      { word: 'übertreffen', japanese: '超える', example: 'Er hat alle Erwartungen übertroffen.', notes: '動詞' },
      { word: 'verwalten', japanese: '管理する', example: 'Er verwaltet das Budget.', notes: '動詞' },
      { word: 'innovieren', japanese: '革新する', example: 'Das Unternehmen muss innovieren.', notes: '動詞' },
      { word: 'gewährleisten', japanese: '保証する', example: 'Das muss gewährleistet werden.', notes: '動詞' },
      { word: 'optimieren', japanese: '最適化する', example: 'Wir müssen den Prozess optimieren.', notes: '動詞' },
      { word: 'integrieren', japanese: '統合する', example: 'Wir müssen das System integrieren.', notes: '動詞' },
      { word: 'legitimieren', japanese: '正当化する', example: 'Wie kann man das legitimieren?', notes: '動詞' },
      // 学術
      { word: 'Forschung', japanese: '研究', example: 'Die Forschung ist abgeschlossen.', notes: '名詞(女性)・学術' },
      { word: 'Experiment', japanese: '実験', example: 'Das Experiment war erfolgreich.', notes: '名詞(中性)・学術' },
      { word: 'Daten', japanese: 'データ', example: 'Die Daten müssen analysiert werden.', notes: '名詞(複数)・学術' },
      { word: 'Theorie', japanese: '理論', example: 'Die Theorie wurde bewiesen.', notes: '名詞(女性)・学術' },
      { word: 'Hypothese', japanese: '仮説', example: 'Wir testen die Hypothese.', notes: '名詞(女性)・学術' },
      { word: 'Schlussfolgerung', japanese: '結論', example: 'Was ist Ihre Schlussfolgerung?', notes: '名詞(女性)・学術' },
      { word: 'beweisen', japanese: '証明する', example: 'Das wurde wissenschaftlich bewiesen.', notes: '動詞・学術' },
      { word: 'beobachten', japanese: '観察する', example: 'Wir beobachten das Verhalten.', notes: '動詞・学術' },
      { word: 'klassifizieren', japanese: '分類する', example: 'Die Daten werden klassifiziert.', notes: '動詞・学術' },
      { word: 'Statistik', japanese: '統計', example: 'Laut Statistik ist das häufig.', notes: '名詞(女性)・学術' },
      { word: 'Methode', japanese: '方法論', example: 'Die Methode ist bewährt.', notes: '名詞(女性)・学術' },
      { word: 'Erkenntnis', japanese: '知見・発見', example: 'Das ist eine wichtige Erkenntnis.', notes: '名詞(女性)・学術' },
      { word: 'Perspektive', japanese: '視点', example: 'Betrachten wir das aus einer anderen Perspektive.', notes: '名詞(女性)・学術' },
      { word: 'Konzept', japanese: '概念', example: 'Das Konzept muss überarbeitet werden.', notes: '名詞(中性)・学術' },
      // 高度形容詞・副詞
      { word: 'nachhaltig', japanese: '持続可能な', example: 'Wir brauchen nachhaltige Lösungen.', notes: '形容詞' },
      { word: 'umfassend', japanese: '包括的な', example: 'Eine umfassende Reform ist notwendig.', notes: '形容詞' },
      { word: 'wesentlich', japanese: '本質的な・かなり', example: 'Das ist wesentlich für den Erfolg.', notes: '形容詞' },
      { word: 'erheblich', japanese: '著しい・かなりの', example: 'Es gibt erhebliche Unterschiede.', notes: '形容詞' },
      { word: 'grundlegend', japanese: '根本的な', example: 'Das ist eine grundlegende Frage.', notes: '形容詞' },
      { word: 'vorübergehend', japanese: '一時的な', example: 'Das Problem ist nur vorübergehend.', notes: '形容詞' },
      { word: 'widersprüchlich', japanese: '矛盾した', example: 'Die Aussagen sind widersprüchlich.', notes: '形容詞' },
      { word: 'maßgeblich', japanese: '決定的な・主要な', example: 'Das war maßgeblich für den Erfolg.', notes: '形容詞' },
      { word: 'unerlässlich', japanese: '不可欠な', example: 'Das ist unerlässlich für das Projekt.', notes: '形容詞' },
      { word: 'eigentlich', japanese: '実は・本来', example: 'Was meinen Sie eigentlich damit?', notes: '副詞' },
      { word: 'letztendlich', japanese: '結局', example: 'Letztendlich haben wir gewonnen.', notes: '副詞' },
      { word: 'allerdings', japanese: 'ただし・確かに', example: 'Allerdings gibt es Probleme.', notes: '副詞' },
      { word: 'inzwischen', japanese: 'その間に・今では', example: 'Inzwischen hat sich viel geändert.', notes: '副詞' },
      { word: 'angesichts', japanese: '〜を考慮すると', example: 'Angesichts der Lage müssen wir handeln.', notes: '前置詞' },
    ]
  }
};
